-- =============================================================================
-- Migration 003: Quiz Questions Table + Corrected Module Titles
-- =============================================================================

-- ── Quiz questions (pre-generated by Spartan Lead Specialist Gem) ─────────────
CREATE TABLE IF NOT EXISTS public.quiz_questions (
  id            TEXT    PRIMARY KEY,
  module_id     TEXT    NOT NULL REFERENCES public.mjm_modules(id) ON DELETE CASCADE,
  sequence      INT     NOT NULL,
  question      TEXT    NOT NULL,
  option_a      TEXT    NOT NULL,
  option_b      TEXT    NOT NULL,
  option_c      TEXT    NOT NULL,
  option_d      TEXT    NOT NULL,
  correct       TEXT    NOT NULL CHECK (correct IN ('A','B','C','D')),
  explanation   TEXT,
  is_critical   BOOLEAN DEFAULT false,
  topic         TEXT,
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(module_id, sequence)
);

-- RLS: operators can read questions for modules visible to them (hard gate applies at mjm_modules)
ALTER TABLE public.quiz_questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "quiz_questions_select" ON public.quiz_questions;
CREATE POLICY "quiz_questions_select" ON public.quiz_questions
  FOR SELECT USING (true);
-- Note: access is gated upstream — if RLS on mjm_modules blocks the module, the
-- operator never reaches this table. Admin upsert uses service role.

-- ── Quiz sessions (active exam tracking) ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.quiz_sessions (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id   UUID        NOT NULL REFERENCES public.operators(id) ON DELETE CASCADE,
  module_id     TEXT        NOT NULL REFERENCES public.mjm_modules(id),
  started_at    TIMESTAMPTZ DEFAULT NOW(),
  submitted_at  TIMESTAMPTZ,
  score         NUMERIC(5,2),
  passed        BOOLEAN,
  critical_fail BOOLEAN     DEFAULT false,
  answers       JSONB,      -- {"q-uuid": "A", ...}
  UNIQUE(operator_id, module_id, started_at)
);

ALTER TABLE public.quiz_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "quiz_sessions_select_own" ON public.quiz_sessions;
CREATE POLICY "quiz_sessions_select_own" ON public.quiz_sessions
  FOR SELECT USING (auth.uid() = operator_id);
-- Writes are service-role only.

-- ── Corrected module titles (actual MJM 2026 curriculum) ─────────────────────
UPDATE public.mjm_modules SET
  title = 'Legal Accreditation & GA 509-3-.01',
  description = 'Establishes the legal boundary of operator authority under GBPDSA. Covers the Georgia Board of Private Detectives and Security Agencies requirements, registration obligations, and the 16-hour annual firearms training mandate for MJM 2026 compliance.'
WHERE id = 'MOD-01';

UPDATE public.mjm_modules SET
  title = 'Justification & Deadly Force — OCGA 16-3-21',
  description = 'Defines the lawful conditions for use of deadly force under Georgia law. Deadly force is justified only to prevent death, great bodily injury, or a forcible felony. Property protection does not justify deadly force.',
  critical_question_ids = ARRAY['q-mod02-scenario1']
WHERE id = 'MOD-02';

UPDATE public.mjm_modules SET
  title = 'The Reasonable Man Doctrine',
  description = 'Prepares the operator for the courtroom audit. Examines Graham v. Connor and objective reasonableness — the law judges by information available at the moment, not 20/20 hindsight. Three-factor Graham standard: Severity, Threat, Resistance.',
  critical_question_ids = ARRAY['q-mod03-reasonableness']
WHERE id = 'MOD-03';

-- Clear any existing questions for these modules before seeding (idempotent re-run)
DELETE FROM public.quiz_questions WHERE module_id IN ('MOD-01', 'MOD-02', 'MOD-03');

-- ── Seed questions for Module 01 ──────────────────────────────────────────────
INSERT INTO public.quiz_questions (id, module_id, sequence, question, option_a, option_b, option_c, option_d, correct, explanation, is_critical, topic)
VALUES
  ('q-mod01-01', 'MOD-01', 1,
   'Which Georgia regulatory body governs the licensing of armed security officers under the MJM 2026 standard?',
   'Georgia Bureau of Investigation (GBI)',
   'Georgia Board of Private Detectives and Security Agencies (GBPDSA)',
   'Georgia Department of Public Safety',
   'Georgia Peace Officer Standards and Training Council (POST)',
   'B',
   'The GBPDSA — operating under GA Code 509-3-.01 — is the sole regulatory authority for armed security officer licensing in Georgia. POST governs sworn law enforcement, not private security.',
   false,
   'Regulatory Authority'),

  ('q-mod01-02', 'MOD-01', 2,
   'Under the MJM 2026 Armed Security standard, how many hours of firearms training are required annually to maintain compliance?',
   '8 hours',
   '12 hours',
   '16 hours',
   '24 hours',
   'C',
   '16 hours of annual firearms training is the MJM 2026 mandate — exceeding the state minimum to ensure operators maintain active proficiency, not just initial certification.',
   true,
   'Compliance Mandate'),

  ('q-mod01-03', 'MOD-01', 3,
   'An operator whose license registration lapses but continues to work armed security is best described as:',
   'An officer operating under a grace period',
   'A liability — not a licensed officer',
   'A provisional operator pending renewal',
   'A contractor exempt from GBPDSA oversight',
   'B',
   'Without a valid GBPDSA registration, the operator has no legal authority. As stated in the module: "Your registration is your lifeblood. Without compliance, you are not an officer; you are a liability."',
   true,
   'Legal Authority'),

  ('q-mod01-04', 'MOD-01', 4,
   'GA Code 509-3-.01 primarily addresses which of the following?',
   'Criminal background check procedures for security applicants',
   'Minimum wage standards for licensed security personnel',
   'Licensing, registration, and training standards for private security agencies',
   'Use of force guidelines for armed officers',
   'C',
   'GA Code 509-3-.01 is the foundational statute establishing licensing and training requirements for private detectives and security agencies operating in Georgia.',
   false,
   'Statutory Knowledge'),

  ('q-mod01-05', 'MOD-01', 5,
   'The primary purpose of the GBPDSA annual training mandate is:',
   'To generate revenue for the state licensing board',
   'To ensure operators maintain active proficiency above minimum certification levels',
   'To satisfy federal firearms dealer requirements',
   'To fulfill HR documentation requirements for security companies',
   'B',
   'The mandate exists to ensure ongoing proficiency. Certification is a starting point, not a permanent credential. The MJM 2026 standard holds operators to a higher operational bar than the state minimum.',
   false,
   'Training Purpose');

-- ── Seed questions for Module 02 ──────────────────────────────────────────────
INSERT INTO public.quiz_questions (id, module_id, sequence, question, option_a, option_b, option_c, option_d, correct, explanation, is_critical, topic)
VALUES
  ('q-mod02-scenario1', 'MOD-02', 1,
   'SCENARIO: A suspect has stolen a laptop from a secured facility and is fleeing on foot. The suspect is unarmed and poses no physical threat to any person. Do you deploy deadly force to stop them?',
   'Yes — protecting company property justifies the use of force',
   'Yes — the theft constitutes a forcible felony under OCGA 16-3-21',
   'No — property alone does not justify deadly force; a life must be threatened',
   'Yes — your post orders authorize force to prevent theft',
   'C',
   'CRITICAL FAIL IF WRONG. Under OCGA 16-3-21, deadly force is only justified to prevent death, great bodily injury, or a forcible felony involving a threat to life. Property recovery never justifies deadly force. This is a non-negotiable disqualifier.',
   true,
   'Deadly Force — Property'),

  ('q-mod02-02', 'MOD-02', 2,
   'Under OCGA 16-3-21, use of deadly force is justified when necessary to prevent which of the following?',
   'Theft of property valued over $5,000',
   'Trespassing on secured premises',
   'Death, great bodily injury, or a forcible felony',
   'Any criminal offense occurring in your post area',
   'C',
   'OCGA 16-3-21 limits justification for deadly force to three conditions: preventing death, preventing great bodily injury, or preventing a forcible felony. All other scenarios fall outside this authorization.',
   true,
   'OCGA 16-3-21'),

  ('q-mod02-03', 'MOD-02', 3,
   'Which of the following best defines a "forcible felony" in the context of OCGA 16-3-21?',
   'Any felony involving property damage over $500',
   'A felony involving the use or threat of physical force against a person',
   'Any offense that requires police response',
   'A felony committed on private property',
   'B',
   'A forcible felony involves actual or threatened physical force against a person — not property offenses. The distinction is critical to lawful use of force decisions.',
   false,
   'Legal Definitions'),

  ('q-mod02-04', 'MOD-02', 4,
   'A subject approaches you aggressively but stops 10 feet away, raises their hands, and says "I''m done." What is your legally correct response under OCGA 16-3-21?',
   'Maintain force posture — verbal compliance may be deceptive',
   'De-escalate and stand down — the immediate threat has ceased',
   'Deploy non-lethal force as a precaution',
   'Detain the subject immediately regardless of compliance',
   'B',
   'When an imminent threat ceases, the legal justification for force also ceases. Continuing to apply force after compliance ends transforms a lawful action into an unlawful one.',
   false,
   'De-escalation'),

  ('q-mod02-05', 'MOD-02', 5,
   'An operator uses deadly force to stop a suspect fleeing with stolen property and claims justification under "protecting the employer''s assets." This action is:',
   'Legally justified under the property protection doctrine',
   'Justified if the employer''s post orders authorize it',
   'Unlawful — property is not a life and does not justify deadly force',
   'Conditionally justified depending on the property''s value',
   'C',
   'No employer post order, company policy, or asset value can override Georgia law. Deadly force to protect property — absent a life threat — is unlawful. Post orders that authorize such force are themselves unlawful.',
   true,
   'Property vs. Life');

-- ── Seed questions for Module 03 ──────────────────────────────────────────────
INSERT INTO public.quiz_questions (id, module_id, sequence, question, option_a, option_b, option_c, option_d, correct, explanation, is_critical, topic)
VALUES
  ('q-mod03-reasonableness', 'MOD-03', 1,
   'The Graham v. Connor standard requires that a use-of-force decision be judged by:',
   'What the officer believed was reasonable after the incident',
   'The outcome of the force application',
   'What a reasonable officer would have done given the same facts at the moment of decision',
   'The supervisor''s post-incident assessment',
   'C',
   'CRITICAL: Graham v. Connor establishes objective reasonableness — the standard is what a reasonable officer would have done with the information available at the moment of decision. Hindsight is explicitly excluded.',
   true,
   'Graham v. Connor'),

  ('q-mod03-02', 'MOD-03', 2,
   'The "20/20 Hindsight Rule" in use-of-force law means:',
   'Officers should use cameras to review incidents after the fact',
   'Courts cannot judge a split-second decision by information that became available after the fact',
   'Officers are given a 20-second window to escalate force',
   'Force decisions must be reviewed within 20 days',
   'B',
   'The 20/20 Hindsight Rule protects officers from being judged by information unknown at the time of decision. Courts must evaluate the decision based only on facts the officer knew at the moment of the trigger press.',
   false,
   'Legal Protection'),

  ('q-mod03-03', 'MOD-03', 3,
   'The three Graham factors used to assess reasonableness of force are:',
   'Speed, distance, and angle of approach',
   'Threat severity, immediacy, and officer training level',
   'Severity of the offense, immediate threat to safety, and active resistance/evasion',
   'Subject size, officer size, and number of bystanders',
   'C',
   'Graham v. Connor identifies three balancing factors: (1) severity of the crime, (2) whether the subject poses an immediate threat to safety, and (3) whether the subject is actively resisting or evading arrest.',
   true,
   'Graham Factors'),

  ('q-mod03-04', 'MOD-03', 4,
   'An operator is sued for excessive force. The plaintiff''s attorney argues the officer should have known the subject was mentally ill and posed no real threat. Under the Reasonable Man Doctrine:',
   'The officer is automatically liable for failing to identify the mental health condition',
   'The officer is judged by what a reasonable officer would have perceived given the observable facts at the time',
   'The officer should have called for backup instead of acting',
   'Mental health awareness training exempts the officer from the Graham standard',
   'B',
   'Objective reasonableness is assessed based on what was observable and knowable at the moment — not what was later discovered. If the subject''s behavior reasonably appeared threatening to a trained officer, the standard may be met.',
   false,
   'Objective Reasonableness');
