-- ============================================================
-- 015_pi_quiz.sql
-- Quiz questions for PI-01 through PI-24
-- MJM 2026 Private Detective curriculum
-- 5 questions per module (PI-01–23) + 10 questions for PI-24
-- ============================================================

DELETE FROM public.quiz_questions WHERE module_id LIKE 'PI-%';

-- ── PI-01 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi01-q1','PI-01',1,'Under OCGA 43-38-18, operating as a private investigator without a current GBPDSA license is classified as:','A civil infraction with a maximum $500 fine','A misdemeanor on first offense and a felony on repeat offense','A regulatory violation handled only by the Board','A felony on first offense regardless of circumstances','B','OCGA 43-38-18 establishes unlicensed PI practice as a misdemeanor on first offense and a felony on subsequent offenses. This is not merely a regulatory matter — it is a criminal offense prosecuted in Superior or State Court.',true,'Licensing'),
('pi01-q2','PI-01',2,'The GBPDSA operates under which Georgia state office?','Georgia Bureau of Investigation','Georgia Department of Public Safety','Secretary of State''s Professional Licensing Boards Division','Georgia Attorney General''s Office','C','The GBPDSA operates under the Secretary of State''s Professional Licensing Boards Division, which houses all professional licensing authorities in Georgia.',false,'Regulatory'),
('pi01-q3','PI-01',3,'Georgia Admin Code 509-3-.06 establishes what requirement for private investigators?','A minimum of 40 hours of annual continuing education','A mandatory 72-hour initial training curriculum','Quarterly ethics training','Annual range qualification','B','GA Admin Code 509-3-.06 mandates a 72-hour initial training curriculum for persons seeking licensure as private investigators in Georgia. This is the statutory basis for the MJM 2026 curriculum.',false,'Compliance'),
('pi01-q4','PI-01',4,'A licensed PI can lawfully compel a witness to remain at a location and answer questions under which authority?','The authority granted by their GBPDSA PI license','The client''s authorization as the engaging party','Citizen''s arrest authority under OCGA 17-4-60','None — PIs have no authority to compel witnesses','D','Private investigators have no authority to compel anyone to remain at a location or answer questions. PIs are private citizens; only sworn peace officers possess detention and compulsion authority.',false,'Authority'),
('pi01-q5','PI-01',5,'A Board disciplinary proceeding against a GBPDSA licensee can be appealed through:','The Georgia Supreme Court directly','The Office of State Administrative Hearings (OSAH)','The Georgia Bureau of Investigation','The Superior Court of Fulton County only','B','Board disciplinary decisions can be appealed through the Office of State Administrative Hearings (OSAH) under the Georgia Administrative Procedure Act (OCGA 50-13). The appeal must be filed within the statutory deadline.',false,'Regulatory');

-- ── PI-02 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi02-q1','PI-02',1,'A PI who submits a factually false investigative report to a client has violated which of the following?','Only the client''s contract rights — no licensing issue','GBPDSA Code of Conduct and OCGA 43-38-11, which are grounds for license revocation','Only applicable if the report was used in court','Federal RICO statutes','B','Submitting a false investigative report violates the GBPDSA Code of Conduct''s prohibition on misrepresentation and constitutes grounds for discipline under OCGA 43-38-11, up to and including license revocation.',true,'Ethics'),
('pi02-q2','PI-02',2,'When a client''s instructions conflict with Georgia law, the correct order of priority for a licensed PI is:','Client instructions first, then law, then public safety','Law first, then public safety, then client instructions','Client instructions and law are equal — PI must balance them','Public safety first, then client, then law','B','The hierarchy is fixed: compliance with law is non-negotiable and supersedes client instructions. Public safety is second, and the client''s legitimate interests are third. This order does not change based on the urgency of the client''s request.',false,'Ethics'),
('pi02-q3','PI-02',3,'A PI who shapes investigative findings to favor the client''s position — by omitting unfavorable evidence from the report — is committing:','A legitimate exercise of professional judgment','A form of fraudulent misrepresentation that violates the GBPDSA Code of Conduct','Advocacy, which is permitted when working for an attorney','A minor procedural issue that does not affect licensing','B','Selective disclosure of findings to favor the client is a form of misrepresentation that violates the GBPDSA Code of Conduct. A PI''s obligation is to report findings accurately, including those that harm the client''s position.',true,'Ethics'),
('pi02-q4','PI-02',4,'Board disciplinary proceedings are:','Private and never disclosed to the public','Public record, accessible by clients and employers','Disclosed only to courts, not the general public','Sealed after 5 years','B','GBPDSA disciplinary proceedings, including complaints, findings, and sanctions, are public record. Any person — including prospective clients, employers, or opposing parties — can access a licensee''s disciplinary history.',false,'Regulatory'),
('pi02-q5','PI-02',5,'Billing fraud — such as inflating hours worked on a case — constitutes:','Only a breach of contract between PI and client','An ethics violation and potential criminal fraud, not merely a contract matter','A minor administrative issue corrected by invoice amendment','A civil matter outside GBPDSA jurisdiction','B','Billing fraud is both a GBPDSA Code of Conduct violation (grounds for license revocation) and potentially criminal fraud under Georgia law. It is not simply a contract dispute — it is dishonest conduct that subjects the PI to both licensing and criminal consequences.',false,'Ethics');

-- ── PI-03 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi03-q1','PI-03',1,'The standard of proof in civil cases that a private investigator''s evidence typically must support is:','Beyond a reasonable doubt','Preponderance of the evidence','Clear and convincing evidence','Probable cause','B','Civil cases apply the preponderance of evidence standard — more likely than not. Most PI work (insurance, domestic, corporate) supports civil proceedings, not criminal prosecutions, which require the much higher beyond a reasonable doubt standard.',false,'Civil Law'),
('pi03-q2','PI-03',2,'The attorney work product doctrine under OCGA 9-11-26(b)(3) protects which category of PI materials from opposing discovery?','All PI materials prepared at any time','Only materials specifically marked as confidential','Materials prepared in anticipation of litigation under attorney direction','Materials related to criminal cases only','C','The work product doctrine protects materials prepared in anticipation of litigation when the PI is working under attorney direction. Materials not prepared for litigation purposes, or not under attorney direction, receive no work product protection.',false,'Evidence'),
('pi03-q3','PI-03',3,'A conflict of interest check before accepting a new engagement should identify:','Whether the prospective client has paid previous PI firms promptly','Prior engagements involving either party or the opposing party','Whether the subject lives within your surveillance range','The client''s credit history','B','A conflict check looks for prior professional relationships with the client, the subject, or any opposing party that could compromise your objectivity or create ethical issues. It is conducted before accepting any engagement.',false,'Business Practice'),
('pi03-q4','PI-03',4,'A written engagement agreement is required:','Only for engagements exceeding $2,500','Only when the client is a business rather than an individual','Before any work begins, regardless of engagement size','Only when the PI anticipates testifying','C','A written engagement agreement should be executed before any work begins on any engagement. It is the PI''s primary protection against billing disputes, scope creep, and claims of unlawful conduct, regardless of the engagement''s size.',false,'Business Practice'),
('pi03-q5','PI-03',5,'Private investigators most commonly testify in legal proceedings as:','Expert witnesses offering professional opinions','Fact witnesses describing personal observations','Character witnesses for clients','Technical advisors to the court','B','Most PI testimony is fact witness testimony — describing what the PI personally observed during the investigation. Expert witness status requires court qualification and is appropriate only for specific methodological testimony.',false,'Testimony');

-- ── PI-04 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi04-q1','PI-04',1,'Georgia criminal law, including the offenses most relevant to PI work, is found primarily in which Title of the OCGA?','Title 43','Title 16','Title 17','Title 50','B','Title 16 of the OCGA (Crimes and Offenses) contains Georgia''s criminal statutes, including the offenses of stalking, trespass, eavesdropping, computer trespass, and impersonation that create direct exposure for private investigators.',false,'Legal Foundations'),
('pi04-q2','PI-04',2,'A standard misdemeanor in Georgia carries a maximum penalty of:','6 months in jail and $500 fine','12 months in jail and $1,000 fine','24 months in jail and $2,500 fine','36 months in jail and $5,000 fine','B','Standard misdemeanors in Georgia carry a maximum of 12 months imprisonment and a $1,000 fine under OCGA 17-10-3. High and aggravated misdemeanors carry 12 months and up to $5,000.',false,'Criminal Law'),
('pi04-q3','PI-04',3,'A felony conviction for a GBPDSA licensee results in:','A 30-day license suspension pending investigation','Automatic license revocation and a 5-year minimum bar from relicensure','A formal hearing with the possibility of retaining the license','Only civil consequences, not licensing consequences','B','Under OCGA 43-38-11, a felony conviction is grounds for automatic license revocation. The minimum bar from relicensure after a felony-based revocation is 5 years.',false,'Licensing'),
('pi04-q4','PI-04',4,'OCGA 16-11-62 prohibits a PI from recording the private conversations of two other persons without consent. Violation of this statute is classified as:','A misdemeanor on first offense','A regulatory violation handled by GBPDSA only','A felony with no misdemeanor option','A civil tort with no criminal consequence','C','OCGA 16-11-62 violations are felonies — there is no misdemeanor option. Recording a private conversation between two persons without consent from at least one of them is a Georgia felony regardless of the PI''s purpose.',true,'Surveillance Law'),
('pi04-q5','PI-04',5,'A PI who enters an unfenced private backyard to get a better camera angle during surveillance — without permission from the property owner — has committed:','A legitimate investigative technique under the plain view doctrine','Criminal trespass under OCGA 16-7-21, regardless of investigative purpose','Only a civil trespass, not a criminal offense','A violation only if the subject observes the PI entering','C','Criminal trespass under OCGA 16-7-21 occurs the moment a person enters private property without authorization. Intent and investigative purpose are irrelevant to the offense — the act of unauthorized entry is sufficient.',true,'Criminal Exposure');

-- ── PI-05 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi05-q1','PI-05',1,'Under OCGA 17-4-60, a Georgia citizen — including a licensed PI — may make a citizen''s arrest when:','Any criminal offense is committed in their presence','A felony is committed in their presence, or they are authorized by a peace officer','They have reasonable suspicion of criminal activity','A crime is reported to them by a credible witness','B','OCGA 17-4-60 limits citizen arrest authority to two narrow circumstances: a felony committed in the citizen''s personal presence, or specific authorization by a peace officer to assist an arrest. No broader authority exists for PIs.',true,'Arrest Authority'),
('pi05-q2','PI-05',2,'A PI who physically prevents a subject from leaving a location without lawful authority has committed:','A permissible investigative detention','False imprisonment under OCGA 16-5-41, a felony','Citizen''s arrest authorized by the PI''s license','A misdemeanor only if the detention exceeds 30 minutes','B','False imprisonment under OCGA 16-5-41 is a felony carrying 1–10 years imprisonment. There is no minimum duration — even a brief, forceful restriction of movement without lawful authority constitutes the offense.',false,'False Imprisonment'),
('pi05-q3','PI-05',3,'The Fourth Amendment''s prohibition on unreasonable searches and seizures applies directly to:','All persons and entities, including private investigators','Only government actors, including law enforcement officers','Licensed professionals, but not private citizens','Only federal government actors, not state agencies','B','The Fourth Amendment is a constitutional constraint on government action only. Private investigators are not government actors and are not directly bound by Fourth Amendment search and seizure restrictions — though the government agent doctrine can create exceptions.',false,'Constitutional Law'),
('pi05-q4','PI-05',4,'Georgia merchant immunity under OCGA 51-7-60, which allows brief detention of suspected shoplifters, applies to:','Any licensed PI working on behalf of a retail employer','Retail merchants and their direct employees only','Any person who observes a theft in progress','All PI licensees during theft investigation assignments','B','Merchant immunity under OCGA 51-7-60 applies specifically to retail merchants and their direct employees in shopkeeper situations. It does not extend to private investigators, even when hired by the retailer.',false,'Civil Law'),
('pi05-q5','PI-05',5,'A private investigator may use physical force against a subject only when:','Authorized to do so by the client in the engagement agreement','The subject is committing a felony in the PI''s presence','Acting in genuine personal self-defense under OCGA 16-3-21','Protecting the client''s property from the subject','C','Georgia PIs are authorized to use force only in genuine personal self-defense under OCGA 16-3-21. Client authorization, property protection, and even witnessing a felony do not independently authorize the use of force.',true,'Use of Force');

-- ── PI-06 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi06-q1','PI-06',1,'The "government agent doctrine" in Fourth Amendment law is relevant to PI work because:','It grants PIs law enforcement search authority when working with police','Conduct by a PI directed by law enforcement may be imputed to the government, potentially triggering Fourth Amendment analysis','It requires PIs to obtain warrants before surveillance','It exempts PIs from OCGA 16-11-62 when working with police','B','If law enforcement significantly participates in or directs a PI''s surveillance, the PI''s conduct may be treated as governmental under the government agent doctrine, making the Fourth Amendment applicable to that conduct.',false,'Constitutional Law'),
('pi06-q2','PI-06',2,'Georgia is classified as a one-party consent state for audio recording. Under OCGA 16-11-66, a PI may lawfully record a conversation without informing all parties when:','All parties are in a public location','The PI is personally a participant in the conversation','The recording is for a legitimate investigative purpose','The retaining attorney authorizes the recording','B','Georgia''s one-party consent rule under OCGA 16-11-66 allows recording of a conversation when at least one party to that conversation consents. The PI is the consenting party only when they personally participate in the conversation.',true,'Recording Law'),
('pi06-q3','PI-06',3,'The hot pursuit doctrine, which allows law enforcement to enter premises without a warrant when pursuing a fleeing felon, applies to private investigators:','In all circumstances where a felony was committed in their presence','Only when explicitly authorized by an accompanying peace officer','Never — this is a law enforcement doctrine that does not extend to PIs','Only during criminal defense investigation assignments','C','Hot pursuit is a law enforcement exception to the warrant requirement. It does not extend to private investigators. A PI who follows a subject into a private building without permission is committing criminal trespass, not exercising a legal doctrine.',false,'Legal Doctrine'),
('pi06-q4','PI-06',4,'A PI who lawfully places a hidden camera in a public parking lot to record a subject''s activities has:','Violated OCGA 16-11-62 by recording without consent','Conducted lawful surveillance in a public space without reasonable expectation of privacy','Committed trespass on public property','Violated federal wiretap law','B','Subjects in public parking lots have no reasonable expectation of privacy. Recording activities visible in a public space from a lawful vantage point does not violate OCGA 16-11-62 and is standard lawful surveillance practice.',false,'Surveillance Law'),
('pi06-q5','PI-06',5,'When a PI observes physical evidence of a crime during lawful surveillance, the correct response is to:','Collect the evidence immediately to preserve it from destruction','Leave the evidence untouched, photograph it in place, document location, and report to retaining attorney or law enforcement','Seal the area and wait for law enforcement','Turn the evidence over to the client','B','PIs have no authority to seize physical evidence — doing so without authorization constitutes evidence tampering under OCGA 16-10-94. The correct response is to document the evidence''s location and condition and report its existence to the retaining attorney or law enforcement.',false,'Evidence Handling');

-- ── PI-07 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi07-q1','PI-07',1,'A PI''s primary obligation upon arriving at or near a crime scene is:','To collect and preserve physical evidence before it is destroyed','To observe and document without touching, moving, or collecting anything','To secure the perimeter and prevent public access','To immediately notify the client of the discovery','B','Scene preservation — not processing — is the PI''s first obligation. Touching, moving, or collecting physical evidence without authorization constitutes evidence tampering under OCGA 16-10-94.',false,'Crime Scene'),
('pi07-q2','PI-07',2,'In Georgia criminal proceedings, polygraph results are admissible:','Automatically, as scientific evidence','Only if both parties stipulate to admissibility','Whenever requested by either party','Only for defense use, not prosecution','B','Georgia courts do not admit polygraph results as evidence without a stipulation from both parties. The results are considered unreliable as a matter of law and must be specifically agreed to before they may be introduced.',false,'Evidence'),
('pi07-q3','PI-07',3,'When photographing evidence at a crime scene, the correct sequence is:','Close-up first, then medium, then establishing','Establishing shot, then medium, then close-up','Randomly, based on what is most important','Only close-ups to save time and storage','B','The correct forensic photography sequence is establishing shot (context) → medium shot (subject within environment) → close-up (specific detail). This three-level sequence creates a photographic narrative that gives the court full context for each piece of evidence.',false,'Documentation'),
('pi07-q4','PI-07',4,'Touching a crime scene without authorization constitutes what offense under Georgia law?','Criminal trespass under OCGA 16-7-21','Evidence tampering under OCGA 16-10-94','Obstruction of justice under OCGA 16-10-24','No offense — only civil liability','B','Evidence tampering under OCGA 16-10-94 prohibits intentionally altering, concealing, destroying, or removing physical evidence. A PI who handles crime scene evidence without authorization has tampered with evidence regardless of their purpose.',false,'Criminal Exposure'),
('pi07-q5','PI-07',5,'GPS geotagging in photographs provides what evidentiary benefit?','Prevents the photograph from being duplicated','Embeds location data in image metadata, corroborating the PI''s field log position','Automatically authenticates the photograph for court use','Replaces the need for a contemporaneous field log','B','GPS geotagging embeds geographic coordinates in the image file metadata, providing an independent corroboration of where the photograph was taken. This coordinates-in-metadata record is compared against the PI''s field log during cross-examination.',false,'Documentation');

-- ── PI-08 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi08-q1','PI-08',1,'Kinesics in investigative interviewing is most accurately described as:','A technique for detecting lies with certainty','The study of nonverbal behavior used to identify productive follow-up questions, not to prove deception','A validated alternative to polygraph testing','A method of establishing subject cooperation through eye contact','B','Kinesics identifies behavioral stress indicators that suggest which topics warrant more detailed questioning. It does not prove deception — stress indicators can arise from nervousness, not dishonesty — and must not be presented as a truth-detection tool.',false,'Interview Technique'),
('pi08-q2','PI-08',2,'The Cognitive Interview technique increases the accuracy of witness statements by:','Using suggestive questions to fill gaps in memory','Encouraging witnesses to report everything remembered and mentally reinstating the context of the event','Confronting witnesses with inconsistencies in their accounts','Interviewing multiple witnesses simultaneously','B','The Cognitive Interview uses mental context reinstatement, encouraging full reporting, temporal variation, and perspective change to enhance the accuracy and completeness of memory recall. It does not use suggestion or confrontation.',false,'Interview Technique'),
('pi08-q3','PI-08',3,'The most productive phase for obtaining voluntary additional information during a PI interview is typically:','The opening rapport-building phase','The formal questioning phase','After the PI closes the notebook and the interviewee thinks the interview is over','After the PI has warned the interviewee about consequences of withholding','C','Research on witness interviews consistently shows that significant additional information often emerges after the formal session appears to have ended — when the interviewee relaxes. PIs should remain attentive and available after closing their notebook.',false,'Interview Technique'),
('pi08-q4','PI-08',4,'A PI who obtains a statement by threatening negative employment consequences if the witness does not cooperate has committed:','A legitimate investigative technique permitted for insurance investigations','Coercion, which voids the testimonial evidence and constitutes a GBPDSA Code of Conduct violation','A minor procedural irregularity that does not affect admissibility','A technique that is lawful because the threat was not physical','B','Coercion — including psychological threats such as implied employment consequences — voids the reliability of the resulting statement, renders it inadmissible, and constitutes a GBPDSA Code of Conduct violation that is grounds for license revocation.',true,'Coercion'),
('pi08-q5','PI-08',5,'At the beginning of every investigative interview, the PI should:','Inform the interviewee that they are legally required to cooperate','Clearly state that participation is voluntary and the interviewee may end the interview at any time','Obtain a recorded oath from the interviewee','Begin questioning immediately to prevent the interviewee from preparing responses','B','Establishing the voluntary nature of the interview at the outset — and documenting that this was communicated — protects the PI from coercion allegations and ensures the resulting statement is admissible.',false,'Interview Protocol');

-- ── PI-09 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi09-q1','PI-09',1,'Defective service of process in a civil case results in:','A minor procedural error the court can waive','The court lacking personal jurisdiction over the defendant, potentially requiring dismissal','A fine against the process server','Automatic re-service by the court clerk','B','Proper service of process is jurisdictionally mandatory. Defective service deprives the court of personal jurisdiction over the defendant. This can result in dismissal of the action, sanctions, and potential liability for the agency that conducted the defective service.',false,'Process Serving'),
('pi09-q2','PI-09',2,'Substituted service of process in Georgia is valid only when:','The process server decides personal service is inconvenient','The named recipient is not available on the first attempt','The server has made documented diligent attempts at personal service and leaves documents with a person of suitable age and discretion at the defendant''s abode','The client requests substituted service in writing','C','Valid substituted service requires prior documented attempts at personal service and service upon a person of suitable age and discretion at the defendant''s usual place of abode. Shortcutting this requirement renders service defective.',true,'Process Serving'),
('pi09-q3','PI-09',3,'A subpoena duces tecum commands the recipient to:','Appear and testify in court','Produce documents or tangible items','Pay a court-ordered fine','Refrain from certain activities pending trial','B','A subpoena duces tecum (from Latin "bring with you") specifically commands production of documents or tangible items. A subpoena ad testificandum commands personal appearance to testify.',false,'Legal Documents'),
('pi09-q4','PI-09',4,'The Driver''s Privacy Protection Act (DPPA) permits private investigators to access state DMV records for which purpose?','Any investigative purpose authorized by the client','Civil, criminal, administrative, or arbitral proceedings — 18 U.S.C. § 2721(b)(4)','Personal background checks on subjects of interest','Any purpose as long as the PI holds a current license','B','The DPPA''s enumerated permissible purposes for PI access to DMV records is specifically limited to connection with civil, criminal, administrative, or arbitral proceedings. Using DMV records for other purposes is a federal crime.',false,'Federal Law'),
('pi09-q5','PI-09',5,'When skip tracing to locate a subject for service, a PI may lawfully use:','Any method that produces a current address quickly','Pretexting as a government official to obtain address from a database','Public records, licensed commercial database searches under permissible purpose, and social media analysis','Accessing the subject''s bank records through an information broker','C','Legal skip tracing is limited to public records, FCRA and DPPA-compliant database searches under permissible purpose, and publicly available information including social media. Pretexting as a government official or accessing private financial records without authorization are federal crimes.',false,'Skip Tracing');

-- ── PI-10 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi10-q1','PI-10',1,'Georgia''s Open Records Act creates a presumption that records maintained by state and local government are:','Confidential unless specifically released by the agency','Open to public inspection, with enumerated exceptions','Available only to licensed professionals including PIs','Accessible only through attorney FOIA requests','B','OCGA 50-18-70 et seq. creates a presumption of public access to all government-maintained records. The agency has the burden to identify a specific statutory exemption to justify withholding any record.',false,'Public Records'),
('pi10-q2','PI-10',2,'A PI who misrepresents their purpose to a commercial database provider in order to access records they would not otherwise be authorized to access has committed:','A minor terms-of-service violation handled between the PI and the database provider','A Computer Fraud and Abuse Act violation and a GBPDSA ethics violation','Only an FCRA violation handled by the FTC','No legal violation if the records themselves are public','B','Misrepresenting purpose to obtain unauthorized database access constitutes a Computer Fraud and Abuse Act (CFAA) violation under 18 U.S.C. § 1030 and violates the GBPDSA Code of Conduct''s prohibition on deceptive conduct.',false,'Database Access'),
('pi10-q3','PI-10',3,'The Driver''s Privacy Protection Act (DPPA) imposes what penalty for unauthorized access to state DMV records?','A warning letter from the FTC','Fines up to $2,500 per violation and civil liability','A mandatory 30-day license suspension by GBPDSA','Criminal prosecution only available to federal agencies','B','The DPPA imposes civil fines of up to $2,500 per unauthorized access and creates civil liability for actual damages. Repeat or systematic violations can also support criminal prosecution.',true,'Federal Law'),
('pi10-q4','PI-10',4,'Under the Fair Credit Reporting Act, a PI who uses consumer report data for surveillance purposes not covered by a FCRA permissible purpose has:','Committed an FCRA violation subject to FTC enforcement and civil liability','Done nothing wrong as long as the data was obtained from a licensed provider','Committed only a licensing violation handled by GBPDSA','Violated the client''s privacy, not the subject''s','B','The FCRA restricts the use of consumer reports to specific permissible purposes. Surveillance is not a permissible FCRA purpose. Using consumer report data for surveillance subjects the PI to FTC enforcement, civil liability from the consumer, and potential criminal charges for willful violations.',false,'FCRA'),
('pi10-q5','PI-10',5,'Before relying on information from a commercial data aggregator in an investigative report, a PI should:','Verify the information against a primary source — court record, direct observation, or official document','Accept the database result as accurate since commercial aggregators guarantee accuracy','Obtain written confirmation from the client that the information is correct','Wait 30 days to confirm the data has not changed','A','Commercial database results are leads, not verified facts. A report that states facts sourced only from database aggregators — without verification against primary sources — is professionally unreliable and will be challenged in court.',false,'Information Sources');

-- ── PI-11 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi11-q1','PI-11',1,'OCGA 16-11-62 prohibits recording a person in a private place without consent. Which of the following constitutes a "private place" under this statute?','A publicly visible front yard','The interior of an enclosed vehicle parked on a public street','A shopping mall food court','A public park','B','The interior of an enclosed vehicle is a private place under OCGA 16-11-62 — the occupant has a reasonable expectation of privacy inside a closed vehicle. Recording into a closed vehicle interior without consent violates the statute.',false,'Surveillance Law'),
('pi11-q2','PI-11',2,'Georgia is a one-party consent state for audio recording. This means a PI may lawfully record audio of a conversation when:','Any person in the vicinity of the recording consents','The recording is for a legitimate investigative purpose even if no party consents','The PI is a participant in the conversation being recorded','The client authorizes the recording in the engagement agreement','C','Georgia''s one-party consent rule (OCGA 16-11-66) allows recording when at least one party to the conversation consents. The PI is the consenting party only when they personally participate in the conversation. Client authorization does not substitute for participant consent.',true,'Recording Law'),
('pi11-q3','PI-11',3,'A PI conducting mobile vehicular surveillance should abort the follow when:','The subject exceeds posted speed limits','The subject demonstrates counter-surveillance awareness (route doubling, waiting, repeated eye contact)','The subject enters a residential neighborhood','The surveillance has continued for more than 2 hours','B','When a subject demonstrates counter-surveillance behavior — route doubling, parking to observe following traffic, repeated eye contact with the surveillance vehicle — the surveillance has been burned. Continuing surveillance of a burned, aware, and potentially frightened subject creates stalking exposure under OCGA 16-5-90.',false,'Surveillance Technique'),
('pi11-q4','PI-11',4,'Under OCGA 16-11-60.1, placing a GPS tracking device on a vehicle requires:','A PI license and client authorization','Written consent of the vehicle owner OR a court order','Consent of the person who most frequently drives the vehicle','Authorization from the registered titleholder only','B','OCGA 16-11-60.1 requires consent of the vehicle owner (not merely the driver) OR a court order to lawfully place a GPS tracker on a vehicle. Client direction, engagement agreements, and driver consent do not satisfy this requirement.',false,'GPS Law'),
('pi11-q5','PI-11',5,'The GPS law question for jointly owned marital vehicles in Georgia is:','Clearly resolved — one spouse''s consent is always sufficient','Clearly resolved — both spouses must always consent','A legal gray area not uniformly resolved by Georgia courts — consulting an attorney before placement is required','Not subject to Georgia law — federal law governs','C','OCGA 16-11-60.1 and the question of whether joint ownership creates consent for GPS placement has not been uniformly resolved by Georgia courts. PIs should obtain written legal analysis from the retaining attorney before placing any tracker on a vehicle where consent is not unambiguous.',true,'GPS Law');

-- ── PI-12 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi12-q1','PI-12',1,'For surveillance video to clearly identify a subject in court, the minimum recommended resolution is:','480p at any frame rate','720p at 24fps','1080p at 30fps','4K at 60fps — anything lower is inadmissible','C','1080p at 30fps is the minimum recommended standard for surveillance video used in legal proceedings. Lower resolution footage struggles to provide the clear facial identification that courts require.',false,'Equipment Standards'),
('pi12-q2','PI-12',2,'The primary advantage of capturing photographs in RAW format (compared to compressed JPEG) for investigative purposes is:','RAW files are smaller and easier to transmit','RAW files are uncompressed originals that are harder to challenge as edited','RAW files are automatically authenticated by the camera','RAW files are required by all Georgia courts','B','RAW capture creates an uncompressed original file that preserves all sensor data and is significantly harder for opposing counsel to challenge as having been digitally altered compared to compressed JPEG files.',false,'Equipment Standards'),
('pi12-q3','PI-12',3,'A PI should synchronize their camera clock before every assignment because:','Camera manufacturers require it for warranty compliance','Timestamp metadata in photographs is compared against field log entries during cross-examination','Unsynchronized cameras produce lower quality video','Federal law requires synchronized timestamps on investigative footage','B','Timestamp metadata embedded in photographs is examined and compared against field log entries during cross-examination. An unsynchronized camera that shows a different time than the field log creates an impeachment opportunity for opposing counsel.',false,'Documentation'),
('pi12-q4','PI-12',4,'When delivering surveillance footage to a retaining attorney for court use, the PI should:','Delete all irrelevant footage to reduce file size','Provide only the most compelling evidence clips','Retain the unedited original and clearly identify any transcoded copies as copies','Convert all footage to the attorney''s preferred format and discard the original','C','The unedited original must always be retained and never deleted. Any copy or transcoded version is clearly identified as a copy, with the original maintained in secure storage as the authenticated version.',false,'Evidence Handling'),
('pi12-q5','PI-12',5,'Computing a SHA-256 hash of a digital evidence file at the time of collection serves what purpose?','It compresses the file for easier transmission','It proves the file''s integrity — that it has not been altered since capture','It automatically uploads the file to secure storage','It creates a visible watermark on the footage','B','A SHA-256 hash is a unique cryptographic fingerprint of a file at a specific moment. Computing it at collection and recording the value allows future verification that the file has not been altered. If the hash value matches on re-computation, the file is forensically identical to the original.',false,'Chain of Custody');

-- ── PI-13 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi13-q1','PI-13',1,'Contemporaneous notes carry greater evidentiary weight than reconstructed notes because:','They are required by GBPDSA regulations','They are written at or near the time of the event, making fabrication and editing less likely','They are always handwritten, which courts prefer','They are stored on encrypted media','B','Contemporaneous notes are presumed to be more accurate and less subject to later editing or fabrication than notes reconstructed from memory days later. Their authenticity is supported by the physical characteristics of field writing and the consistency of timestamps.',false,'Documentation'),
('pi13-q2','PI-13',2,'In a field log entry for surveillance, describing a subject as "appearing to be in pain" is problematic because:','It requires medical licensing to observe pain','It is an opinion, not an observation — courts may strike PI opinion testimony','It is too subjective for legal proceedings unless corroborated by video','All of the above','B','Characterizations like "appearing to be in pain" are opinions — the PI is inferring an internal state from external behavior. Courts expect PIs to testify to observations, not interpretations. The proper testimony is a specific description of the observed physical behavior.',false,'Documentation'),
('pi13-q3','PI-13',3,'The attorney work product doctrine (OCGA 9-11-26) protects a PI''s materials from opposing discovery when:','The PI holds a current GBPDSA license','The PI is working under attorney direction in anticipation of litigation','The case involves criminal charges','The PI has designated materials as confidential','B','Work product protection requires that the materials were prepared in anticipation of litigation and that the PI was working under the direction of a licensed attorney for that litigation. These conditions are both required.',false,'Legal Protection'),
('pi13-q4','PI-13',4,'Which category of work product receives the strongest protection from opposing discovery?','Fact work product — underlying observations and logs','Opinion work product — the PI''s mental impressions and conclusions','Equipment and methodology records','Billing records','B','Opinion work product — including a PI''s analytical conclusions, theories, and mental impressions — receives nearly absolute protection from opposing discovery. Fact work product (underlying observations) receives qualified protection that can be overcome.',false,'Legal Protection'),
('pi13-q5','PI-13',5,'If a PI types up a clean version of their handwritten field notes for readability, they must:','Destroy the handwritten originals to avoid confusion','Retain the original handwritten notes and note that the typed version is a transcription','Certify the typed version as the original','Submit only the typed version and not disclose the handwritten version exists','B','Original handwritten notes must be retained — they are discovery-responsive and may need to be produced. The typed transcription should be clearly labeled as such. Destroying originals to replace them with a typed version can constitute spoliation of evidence.',false,'Documentation');

-- ── PI-14 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi14-q1','PI-14',1,'The minimum recommended retention period for PI billing records under Georgia''s contract statute of limitations (OCGA 9-3-24) is:','2 years','4 years','6 years','10 years','C','OCGA 9-3-24 establishes a 6-year statute of limitations for written contract disputes in Georgia. PI billing records should be retained for a minimum of 6 years to ensure availability in any billing dispute that arises within the limitations period.',false,'Business Practice'),
('pi14-q2','PI-14',2,'An investigative report''s conclusions section should be limited to:','Opinions formed by the PI over the course of the investigation','What the facts directly support — with speculation and inference excluded','Recommendations for further investigation','The PI''s professional assessment of the subject''s credibility','B','Conclusions in an investigative report must be directly and specifically supported by documented findings. Speculation, inference, and professional opinion beyond what the facts establish must be excluded from the conclusions section.',false,'Report Writing'),
('pi14-q3','PI-14',3,'Chain of custody documentation for evidence requires:','A signature from the client authorizing each transfer','A documented, unbroken record of every person who accessed the evidence from collection to presentation','Only final disposition documentation — not intermediate transfers','A court-ordered chain of custody form for each piece of evidence','B','Chain of custody is an unbroken record of every access — by anyone, for any reason — from the moment of collection through presentation. Gaps in the chain are authentication vulnerabilities that opposing counsel will exploit.',true,'Chain of Custody'),
('pi14-q4','PI-14',4,'An attorney who instructs a PI to destroy billing records that have been subpoenaed is:','Exercising legitimate attorney-client privilege over business records','Asking the PI to commit evidence tampering under OCGA 16-10-94','Following standard litigation management practice','Protecting the client''s confidential financial information','B','Destroying subpoenaed records is evidence tampering under OCGA 16-10-94, regardless of who gives the instruction. An attorney who instructs a PI to destroy subpoenaed documents is asking the PI to commit a crime.',false,'Ethics'),
('pi14-q5','PI-14',5,'Client identifying information and case details may be shared outside the engagement agreement''s authorized parties:','When the client consents to disclosure','Only as required by law or court order, or with client consent','When the sharing party believes disclosure serves the public interest','At the PI''s discretion if the case is closed','B','Client confidentiality is a GBPDSA Code of Conduct obligation. Disclosure of client or case information outside authorized parties is permissible only with client consent or as required by law (including valid legal process). Even after case closure, confidentiality obligations persist.',false,'Confidentiality');

-- ── PI-15 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi15-q1','PI-15',1,'A PI testifying about what they personally observed during surveillance is testifying as a:','Expert witness offering specialized opinion','Fact witness describing direct observations','Lay opinion witness','Character witness','B','Describing personal observations is the definition of fact witness testimony. A PI becomes an expert witness only when the court qualifies them to offer opinions in a specialized field — which requires a separate qualification process.',false,'Testimony'),
('pi15-q2','PI-15',2,'During direct examination, when a PI does not remember a specific detail exactly, the appropriate response is:','Guess based on most likely scenario','State the most favorable answer to the client''s position','Say "I would need to check my field notes" and offer to review them','Decline to answer and defer to the attorney','C','Admitting a memory limitation and offering to check contemporaneous field notes is the professional and legally appropriate response. Guessing creates false testimony; falsely claiming certainty damages credibility when the notes contradict the guess.',false,'Testimony'),
('pi15-q3','PI-15',3,'Georgia adopted the Daubert standard for expert testimony reliability in what year?','1993, following the federal Supreme Court decision','2000, as part of the Georgia Evidence Reform Act','2013, when Georgia adopted the new Evidence Code','2020, following legislative amendment','C','Georgia adopted the federal Daubert standard for expert witness reliability through its new Evidence Code effective January 1, 2013. Prior to this, Georgia applied the older Frye general acceptance standard.',false,'Evidence Standards'),
('pi15-q4','PI-15',4,'Perjury under OCGA 16-10-70 is classified as:','A misdemeanor for a first offense','A civil matter that does not carry criminal penalties','A felony carrying 1 to 10 years imprisonment','A GBPDSA ethics violation but not a criminal offense','C','Perjury is a felony under OCGA 16-10-70 carrying a sentence of 1 to 10 years imprisonment. It also constitutes an automatic ground for GBPDSA license revocation. It is both a criminal offense and a licensing consequence.',true,'Perjury'),
('pi15-q5','PI-15',5,'If a retaining attorney instructs a PI to testify in a manner the PI knows to be false, the PI should:','Comply — the attorney has authority over witness preparation','Comply only if the misstatement is about a minor detail','Refuse, document the instruction, and consult their own counsel if necessary','Ask the court for guidance before testifying','C','No attorney instruction can require a PI to commit perjury. The PI must refuse any instruction to testify falsely, document the instruction in writing, and consult their own legal counsel if the pressure to testify falsely continues.',false,'Ethics');

-- ── PI-16 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi16-q1','PI-16',1,'Felony criminal cases in Georgia are filed in and heard by:','Magistrate Court','State Court','Superior Court','Municipal Court','C','Superior Court is the court of general jurisdiction in Georgia and handles all felony criminal matters. Misdemeanors are heard in State Court. Magistrate Court handles warrants, probable cause hearings, and small civil claims.',false,'Court Structure'),
('pi16-q2','PI-16',2,'PACER provides electronic access to records from which courts?','Georgia Superior and State Courts','Federal district courts, bankruptcy courts, and appellate courts','All state and federal courts in the United States','Georgia courts only for cases involving federal questions','B','PACER (Public Access to Court Electronic Records) is a federal judiciary system that provides access to U.S. District Courts, U.S. Bankruptcy Courts, and U.S. Courts of Appeals. It does not include state court records.',false,'Court Records'),
('pi16-q3','PI-16',3,'Georgia death certificates are classified as:','Restricted vital records accessible only to family members','Public records accessible by any person','Semi-public records requiring a showing of personal interest','Sealed records accessible only through court order','B','Georgia death certificates are public records and can be accessed by any person without a showing of personal interest. This distinguishes them from birth certificates, which require demonstration of personal interest.',false,'Vital Records'),
('pi16-q4','PI-16',4,'Under Georgia''s Open Records Act, a state agency must respond to a records request within:','20 business days','10 business days','3 business days','30 calendar days','C','Georgia''s Open Records Act (OCGA 50-18-70) requires state and local agencies to respond to records requests within 3 business days, either by providing the records or explaining why they are being withheld under an applicable exemption.',false,'Open Records'),
('pi16-q5','PI-16',5,'In a criminal case, which document typically provides the most detailed factual account of the admitted facts and is therefore most useful for PI background research?','The indictment','The arrest warrant','The plea agreement','The police incident report','C','A plea agreement requires the defendant to admit specific factual conduct. These admissions — required for the plea to be accepted — provide the most detailed and reliable factual account available in a resolved criminal matter, making them particularly valuable for background investigation research.',false,'Research Technique');

-- ── PI-17 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi17-q1','PI-17',1,'Brady v. Maryland established that the prosecution must disclose to the defense:','All evidence in the prosecution''s possession','All material exculpatory evidence that could tend to prove innocence or reduce punishment','Only physical evidence discovered at the crime scene','Only evidence that the defendant specifically requests','B','Brady v. Maryland (1963) held that suppression of material exculpatory evidence by the prosecution violates due process. Material evidence is any evidence that, if disclosed, creates a reasonable probability of a different outcome.',false,'Criminal Defense'),
('pi17-q2','PI-17',2,'When re-interviewing a witness who previously spoke with police, a PI must:','Begin by presenting the police version of events to establish a comparison baseline','Identify themselves as a licensed PI working for the defense and make clear participation is voluntary','Not conduct the interview without law enforcement present','Obtain a court order authorizing the re-interview','B','Re-interview of police-interviewed witnesses is lawful and a core defense PI function. The PI must clearly identify their role and professional affiliation and make plain that the witness''s participation is completely voluntary.',false,'Defense Investigation'),
('pi17-q3','PI-17',3,'Witness tampering under OCGA 16-10-93 is:','A misdemeanor when committed by a licensed PI','A felony — applies to anyone who intimidates, threatens, or interferes with a witness','Only applicable to conduct by prosecutors or defense attorneys','A regulatory matter handled by GBPDSA, not the courts','B','Witness tampering under OCGA 16-10-93 is a felony applicable to anyone — including private investigators — who intimidates, threatens, or otherwise interferes with a witness in a legal proceeding.',false,'Criminal Exposure'),
('pi17-q4','PI-17',4,'When a PI working for a defense attorney discovers evidence that is unfavorable to the client, they should:','Discard the evidence to prevent it from being used against the client','Report it to the retaining attorney immediately','Sit on the evidence until the attorney asks specifically','Share it directly with the prosecution as a Brady obligation','B','A defense PI''s obligation is to report all findings — favorable and unfavorable — to the retaining attorney. The attorney then makes legal decisions about how to handle unfavorable evidence. The PI does not make disclosure decisions independently.',false,'Defense Ethics'),
('pi17-q5','PI-17',5,'A PI visiting an incarcerated client at a jail must:','Visit as a personal visitor to avoid drawing attention to the legal team','Log the visit as a professional/legal visit authorized through the retaining attorney','Bring copies of case documents for the client to review without clearing them with the facility','Have law enforcement accompaniment for all visits','B','Visits to incarcerated clients must be logged and authorized as legal/professional visits through the retaining attorney''s visiting authority. Visiting as a personal visitor when conducting legal business forfeits the attorney-client privilege protection for the communication.',false,'Incarcerated Clients');

-- ── PI-18 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi18-q1','PI-18',1,'In Georgia, undercover investigation by a licensed PI is:','Absolutely prohibited by the GBPDSA Code of Conduct','Lawful within specific legal limits, including prohibitions on impersonation and entrapment','Lawful only when authorized by law enforcement','Lawful only when the client is an attorney','B','Undercover investigation is not categorically prohibited in Georgia. PIs may operate under a cover identity within legal limits — they may not impersonate law enforcement, claim authority they don''t have, or induce subjects to commit crimes.',false,'Undercover Law'),
('pi18-q2','PI-18',2,'Entrapment in the PI context occurs when:','A PI observes a crime that a subject commits independently','A PI induces a subject to commit an offense they would not have committed independently','A PI uses a cover identity to gain access to a setting','A PI records a conversation without the subject''s knowledge','B','Entrapment is the inducement of criminal conduct in a person who would not have independently engaged in that conduct. For PIs, engineering a situation specifically designed to cause a subject to commit a crime is entrapment — absolutely prohibited.',true,'Entrapment'),
('pi18-q3','PI-18',3,'A cover identity used in undercover PI work should NOT include:','A fictitious name in a non-legal context','A false claim to hold a professional license such as attorney, doctor, or CPA','A fictional employer in a non-regulated industry','A personal backstory that does not require law enforcement affiliation','B','Falsely claiming to hold a professional license (attorney, physician, CPA) is fraud. A PI may use a fictional personal or business identity within limits — but falsely claiming a regulated professional credential creates criminal fraud exposure.',false,'Undercover Technique'),
('pi18-q4','PI-18',4,'During undercover operations, a PI may lawfully record audio of conversations they personally participate in because:','Client authorization covers all recording during PI engagements','Federal law permits undercover recording in all circumstances','Georgia''s one-party consent rule (OCGA 16-11-66) applies — the PI is the consenting participant','The subject implicitly consents by engaging in the conversation','C','The PI is a participant in conversations they personally join during undercover operations. As a participant, the PI is the consenting party under Georgia''s one-party consent rule, making audio recording lawful.',false,'Recording Law'),
('pi18-q5','PI-18',5,'Leaving an unmanned audio recorder in a room where the subject will have conversations with others — when the PI will not be present — is:','Permitted under one-party consent if the client is a party to the conversation','A OCGA 16-11-62 felony — no party to those conversations has consented','Permitted under the work product doctrine','A misdemeanor if the subject discovers the device','B','An unmanned recorder capturing conversations between parties other than the PI is not covered by the one-party consent rule because the PI is not a participant. Recording third-party conversations without the consent of at least one participant violates OCGA 16-11-62, a felony.',false,'Recording Law');

-- ── PI-19 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi19-q1','PI-19',1,'In Georgia divorce proceedings, evidence of adultery is relevant to which determination?','Division of marital property','Alimony determinations under OCGA 19-6-1','Custody of minor children','All of the above','B','Under OCGA 19-6-1, adultery is a factor in alimony determinations in Georgia — an adulterous spouse is generally barred from receiving alimony. Adultery evidence is less directly relevant to property division and custody.',false,'Domestic Investigation'),
('pi19-q2','PI-19',2,'Georgia stalking law under OCGA 16-5-90 applies to PI surveillance when:','The PI''s surveillance produces any evidence','The subject becomes aware of the surveillance under any circumstances','The surveillance generates conduct that would cause a reasonable person in the subject''s position to feel harassed and intimidated','The surveillance continues for more than 5 days','C','The stalking statute requires that the surveillance be for the purpose of harassing and intimidating — assessed by an objective reasonable person standard. A PI whose surveillance has been burned and is producing fear in the subject has crossed into stalking territory regardless of their subjective investigative intent.',true,'Stalking Law'),
('pi19-q3','PI-19',3,'A PI observing children during a domestic investigation has what obligation if they observe conditions indicating danger to a child?','Report the observation to the client only','Maintain confidentiality as specified in the engagement agreement','Report to the Georgia Division of Family and Children Services (DFCS) regardless of client instruction','Include the observation in the final report without immediate action','C','Child safety obligations override client confidentiality. A PI who observes conditions indicating danger to a child has a duty to report to DFCS. Client instructions cannot override this obligation.',false,'Child Safety'),
('pi19-q4','PI-19',4,'Aggravated stalking under OCGA 16-5-91 occurs when stalking is committed:','By a licensed PI without a written engagement agreement','In violation of a condition of release, protective order, or injunction','By two or more persons acting in concert','Across more than one county','B','Aggravated stalking under OCGA 16-5-91 is a felony that occurs when stalking conduct is committed in violation of a bond condition, protective order, or other injunction. A PI conducting surveillance that circumvents a protective order can face felony charges.',false,'Stalking Law'),
('pi19-q5','PI-19',5,'Client communication frequency in high-conflict domestic investigations should be:','As frequent as the client requests — this builds trust','On a real-time basis during active surveillance to maintain client confidence','Established at intake as scheduled updates — not real-time surveillance commentary','Unlimited — the client has paid for the service','C','Establishing scheduled, limited communication cadence at intake prevents client-driven escalation of surveillance beyond legal limits and maintains professional distance. Real-time commentary during surveillance creates client pressure for immediate tactical decisions the PI should be making independently.',false,'Client Management');

-- ── PI-20 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi20-q1','PI-20',1,'A PI reporting on a workers'' compensation fraud case should describe a claimant''s physical activities as:','Specifically observed behaviors — "subject carried a box up three stairs" — not medical conclusions','Evidence that the subject is not injured and has committed fraud','Inconsistent with their claimed disability, with the PI''s medical assessment included','As assessed by the PI based on their professional experience','A','Investigative reports must state specific factual observations. "Subject is not injured" is a medical conclusion the PI is not qualified to make. "Subject carried a 30-40lb box up three stairs" is a specific factual observation. The medical conclusion is for physicians and attorneys to draw.',false,'Report Writing'),
('pi20-q2','PI-20',2,'SIU (Special Investigative Unit) documentation protocols:','Are optional guidelines that PIs may follow at their discretion','Must be followed precisely — deviation can result in evidence rejection by the carrier','Apply only to video evidence, not written reports','Are standardized identically across all insurance carriers','B','Each carrier''s SIU has specific documentation requirements for format, naming, and submission. Deviation from these requirements — even if the underlying investigation is sound — can result in evidence rejection and professional consequences for the PI.',false,'Insurance Investigation'),
('pi20-q3','PI-20',3,'During deposition in an insurance fraud case, the most common challenge to PI testimony regarding subject identification is:','That the PI was not physically present during surveillance','That the footage does not conclusively identify the specific claimant','That the PI violated OCGA 16-11-62 during surveillance','That the PI lacks medical expertise to interpret the footage','B','Opposing counsel frequently challenges subject identification — arguing the PI filmed someone who looks like the claimant rather than the claimant themselves. The PI must be able to articulate specifically how they identified the subject at the scene.',false,'Testimony'),
('pi20-q4','PI-20',4,'A PI who conducts surveillance only on days when a subject is known to be active and then presents that as a complete surveillance record is vulnerable to:','No challenge — surveillance scheduling is a professional discretion matter','A selection bias challenge in deposition or court','A chain of custody challenge','An OCGA 16-11-62 challenge','B','Documenting only productive days creates the appearance that unfavorable (inactive) days were concealed. PIs should document every surveillance period, including inactive days, to demonstrate that their record reflects the subject''s actual pattern of activity.',false,'Evidence Integrity'),
('pi20-q5','PI-20',5,'A staged accident — in which participants deliberately cause a collision to generate fraudulent insurance claims — is an example of which category of insurance fraud?','Workers'' compensation fraud','Life insurance fraud','Auto insurance fraud — specifically an organized fraud scheme','Property insurance fraud','C','Staged accidents are a form of auto insurance fraud. They often involve organized rings with multiple participants, including staged pedestrian incidents, sideswipes, and rear-end collisions with pre-recruited "victims."',false,'Fraud Types');

-- ── PI-21 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi21-q1','PI-21',1,'The Computer Fraud and Abuse Act (CFAA), 18 U.S.C. § 1030, prohibits:','Using a computer without a specific brand of licensed software','Accessing a computer system without authorization or in excess of authorized access','Collecting public information from websites accessible to everyone','Using commercial database aggregators for PI research','B','The CFAA prohibits unauthorized access to computer systems and exceeding authorized access. It applies regardless of the PI''s purpose — a client''s instruction to access another person''s account does not create CFAA authorization.',false,'Federal Law'),
('pi21-q2','PI-21',2,'Forensic imaging of a digital device — as opposed to a standard file copy — is required to:','Make the evidence fit on a USB drive for transport','Capture deleted files, slack space, and metadata that a standard copy omits','Comply with GBPDSA licensing requirements for digital evidence','Encrypt the evidence for secure storage','B','Forensic imaging creates a bit-for-bit copy of the entire storage media including deleted files, unallocated space, and system metadata. A standard file copy captures only active files and misses critical forensic data.',false,'Digital Forensics'),
('pi21-q3','PI-21',3,'OSINT (Open Source Intelligence) is legally constrained by the distinction between:','Information found through a paid database versus free online sources','Publicly accessible information versus information behind any form of login or access control','Information about businesses versus information about individuals','Federal versus state jurisdiction over information sources','B','The OSINT legal line is the public/private distinction. Genuinely public information — accessible without a login or access barrier — is lawful to collect. Information behind any access control (login, paywall, friend request) is not public and accessing it requires authorization.',false,'OSINT'),
('pi21-q4','PI-21',4,'A PI who receives a client''s former employee''s account credentials through company IT logs and uses them to access that person''s personal cloud storage has:','Lawfully accessed company property','Committed a CFAA violation — accessing another person''s account without authorization','Exercised legitimate investigative authority under the client''s direction','Committed only an ethical violation without criminal consequence','B','Accessing a personal cloud storage account using credentials obtained without the account owner''s consent is unauthorized access under the CFAA, regardless of how the credentials were obtained. The client''s direction does not create authorization.',false,'CFAA'),
('pi21-q5','PI-21',5,'When a case requires forensic examination of a suspect''s personal computer, the PI who is not forensic-imaging certified should:','Perform the imaging as carefully as possible and document the methodology','Power off the device and immediately hand it to law enforcement','Retain a certified digital forensics examiner and document the chain of custody through the handoff','Perform a standard file copy to capture the most important files','C','Forensic imaging without certification risks inadmissible evidence and potential destruction of data through improper procedures. The correct action is to preserve the physical device, document the chain of custody, and hand it off to a qualified forensic examiner.',false,'Digital Forensics');

-- ── PI-22 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi22-q1','PI-22',1,'In Georgia, a private investigator conducting armed executive protection work must hold:','Only their individual GBPDSA PI license','Both an individual armed security officer license and work under a licensed agency','A federal contractor license for protective work','A specific GBPDSA Executive Protection endorsement','B','Armed executive protection requires the same GBPDSA armed security officer (individual) and agency licensing as all armed security work in Georgia. There is no separate EP license — armed EP practitioners operate under the standard armed security license framework.',false,'Licensing'),
('pi22-q2','PI-22',2,'Threat assessment in an EP context involves:','Physically testing security perimeters around the principal','Identifying persons of concern, assessing threat credibility, and recommending proportionate countermeasures','Installing surveillance systems at the principal''s residence','Negotiating with potential threat actors on behalf of the principal','B','Threat assessment is an intelligence-gathering and analysis function: identify persons of concern, assess whether threats are specific or aspirational, evaluate means and opportunity, and recommend countermeasures. It is not a physical security function.',false,'Threat Assessment'),
('pi22-q3','PI-22',3,'Advance work for an executive protection operation includes:','Conducting surveillance on persons of concern at the event venue','Route surveys, venue security assessments, and vulnerability reports delivered before the principal moves','Physical training of security personnel','Negotiating terms with the venue''s security staff','B','Advance work is reconnaissance and pre-event planning: route surveys, venue assessments including sightlines and emergency exits, and vulnerability reports. It is delivered before the principal moves through the location so the team can plan accordingly.',false,'Advance Work'),
('pi22-q4','PI-22',4,'When a PI conducting advance work discovers that a person of concern has RSVP''d to the principal''s event under a different name, the correct immediate action is:','Confront the person of concern at the event venue','Report the finding to the protective team lead and the retaining attorney or client before the event','Wait to see if the person appears and behave normally upon arrival','Cancel the event on your own authority','B','Intelligence findings — especially persons of concern with attendance at the principal''s event — must be reported immediately to the protective team lead and to the retaining attorney or client. The PI does not make the attendance or cancellation decision independently.',false,'Threat Response'),
('pi22-q5','PI-22',5,'Abort and escalation criteria in an executive protection operation should be:','Determined in real time by the lead protective agent during the event','Defined in advance so every team member knows exactly what triggers a response','Left vague to allow flexibility in unpredictable situations','Set by the principal based on their personal comfort level','B','Pre-defined abort and escalation criteria ensure that every team member acts consistently when a trigger event occurs, without waiting for ad hoc decision-making under pressure. Vague criteria produce inconsistent responses and increase risk.',false,'Operations');

-- ── PI-23 ─────────────────────────────────────────────────────────────────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi23-q1','PI-23',1,'A licensed PI operating under their individual license through a corporate entity without also obtaining an agency license for that entity is:','Compliant — the individual license covers all business activities','In violation of OCGA 43-38-18 — the business entity requires its own GBPDSA agency license','Required to list the corporate entity on their individual license renewal','Exempt if the corporation has fewer than 5 employees','B','Both the individual PI license and a separate agency license for the business entity through which the PI operates are required. Using a corporation, LLC, or other entity to accept PI engagements without that entity''s own agency license is unlicensed practice under OCGA 43-38-18.',false,'Licensing'),
('pi23-q2','PI-23',2,'Client funds received as retainers must be held in:','The PI''s general business operating account for convenience','A separate client trust account — not commingled with operating funds','A savings account at the PI''s personal bank','Any account, as long as detailed records are maintained','B','Retainer funds belong to the client until earned. Commingling client funds with operating funds is an ethics violation and can constitute conversion. Client funds must be held in a dedicated trust account and only transferred to operating accounts as fees are earned.',false,'Financial Compliance'),
('pi23-q3','PI-23',3,'An engagement agreement that specifies a PI''s hourly rate but does not cap the maximum number of hours creates:','A clear contract — the client pays for all hours worked','An ambiguous situation where the client can successfully dispute any hours beyond an implied estimate','A billing dispute vulnerability that should be resolved by adding an estimated hours cap or requiring written client approval to exceed specified limits','A contract that is unenforceable in Georgia','C','An uncapped hourly agreement gives the PI legal authority to bill for all hours worked, but creates a dispute vulnerability when hours significantly exceed informal estimates. Best practice is an explicit estimated hours range with written authorization required to exceed it.',false,'Contract'),
('pi23-q4','PI-23',4,'Errors and Omissions (E&O) insurance for a PI agency covers:','Bodily injury to third parties during surveillance operations','Claims that the PI''s professional services caused harm through negligence, errors, or omissions','Theft of PI agency equipment','Workers'' compensation claims from agency employees','B','E&O insurance — professional liability coverage — protects against claims that the PI''s professional services were negligently performed or produced incorrect results that caused harm. It does not cover bodily injury (general liability) or employee injuries (workers'' comp).',false,'Insurance'),
('pi23-q5','PI-23',5,'Time entries in PI billing records should be recorded:','At the end of each billing cycle by reviewing the case file','Contemporaneously — at the time the work is performed','Weekly in a batch entry at the end of each week','Only for billable activities over one hour in duration','B','Contemporaneous time records — entered at the time the work is performed — are the only billing records that withstand scrutiny in a billing dispute. Reconstructed or batch-entered time records are subject to credibility challenges and may be unenforceable.',false,'Billing');

-- ── PI-24: Final Accreditation Examination (10 questions, 3 critical) ─────────
INSERT INTO public.quiz_questions (id,module_id,sequence,question,option_a,option_b,option_c,option_d,correct,explanation,is_critical,topic) VALUES
('pi24-q1','PI-24',1,'The GBPDSA''s authority to discipline a licensed PI includes which of the following actions?','Issue, deny, suspend, revoke, audit, and impose civil penalties','Issue and renew licenses only — discipline is handled by courts','Impose criminal penalties directly without court involvement','Only revoke licenses — suspension and civil penalties require court order','A','The GBPDSA has full disciplinary authority including issuing, denying, suspending, and revoking licenses; auditing training records; investigating complaints; and imposing civil penalties. Criminal prosecution is a separate function of the courts.',false,'Regulatory'),
('pi24-q2','PI-24',2,'Under OCGA 16-11-62, which of the following surveillance activities by a PI is lawful without any consent?','Recording audio of two persons conversing in their vehicle','Photographing a subject walking on a public sidewalk','Placing a camera inside a subject''s residence','Recording audio of a neighbor''s front porch conversation','B','A subject walking on a public sidewalk has no reasonable expectation of privacy. Photographing them from a public vantage point requires no consent and is lawful under OCGA 16-11-62. All other options involve either private places or unconsented audio recording of third-party conversations.',false,'Surveillance Law'),
('pi24-q3','PI-24',3,'A Georgia PI who accesses a subject''s personal email account using credentials provided by the client, without the account owner''s consent or a court order, has committed:','An ethical violation only — no criminal exposure if the client authorized it','Violations of the Computer Fraud and Abuse Act (CFAA) and potentially OCGA 16-9-93, regardless of client authorization','A permissible investigative technique when employed by a licensed PI','A minor regulatory violation handled by GBPDSA','B','Unauthorized access to a personal email account violates the CFAA (18 U.S.C. § 1030) and potentially OCGA 16-9-93 (computer trespass). Client authorization does not create account-owner consent. Both state and federal criminal exposure attach to this conduct.',true,'Federal Law'),
('pi24-q4','PI-24',4,'The standard of proof applicable to most civil litigation that PI evidence supports is:','Beyond a reasonable doubt','Clear and convincing evidence','Preponderance of the evidence','Probable cause','C','The preponderance of the evidence standard — more likely than not — governs most civil cases including insurance disputes, domestic proceedings, and corporate matters. PI evidence is typically gathered to meet this standard.',false,'Civil Law'),
('pi24-q5','PI-24',5,'A chain of custody log for digital evidence must document:','The file name and size only','Every person who accessed the evidence, when, and for what purpose, from collection through presentation','Only the initial collection and final presentation','Only transfers between the PI and the retaining attorney','B','Chain of custody is a complete, unbroken record of every access by every person from the moment of collection through court presentation. Any undocumented access — including the PI''s own access to their own files — creates an authentication vulnerability.',false,'Chain of Custody'),
('pi24-q6','PI-24',6,'The Georgia Open Records Act''s response deadline for state and local agency records requests is:','20 business days (same as federal FOIA)','10 business days','3 business days','30 calendar days','C','Georgia''s ORA (OCGA 50-18-70) requires state and local agencies to respond to records requests within 3 business days — significantly faster than federal FOIA''s 20 business day standard.',false,'Public Records'),
('pi24-q7','PI-24',7,'Perjury under OCGA 16-10-70 cannot be excused by which of the following:','The fact that the false statement seemed minor','The retaining attorney''s instruction to simplify testimony','The client''s urgency regarding the case outcome','All of the above — perjury has no legal excuse in judicial proceedings','D','Perjury is a felony with no legal excuse. Attorney instructions, client pressure, and perceived minor significance of the false statement are irrelevant. A PI who testifies falsely under oath has committed perjury regardless of who instructed them or why.',true,'Perjury'),
('pi24-q8','PI-24',8,'The Driver''s Privacy Protection Act''s permissible purpose for PI access to DMV records is:','Any licensed PI investigation','Connection with civil, criminal, administrative, or arbitral proceedings','Background screening for employment purposes','Any purpose as long as the requestor holds a PI license','B','The specific DPPA permissible purpose for PI access to DMV records is limited to connection with civil, criminal, administrative, or arbitral proceedings under 18 U.S.C. § 2721(b)(4). General PI investigative purposes without a specific proceeding do not satisfy this requirement.',false,'Federal Law'),
('pi24-q9','PI-24',9,'A citizen''s arrest under OCGA 17-4-60 is lawful for a PI when:','The PI has reasonable suspicion of any criminal activity','A misdemeanor is committed in the PI''s presence','A felony is committed in the PI''s personal presence','The client authorizes the PI to detain the subject','C','Georgia''s citizen arrest statute limits the authority to felonies committed in the arresting person''s personal presence. PIs have no additional arrest authority beyond this civilian standard. Detaining a subject on any other basis is false imprisonment.',true,'Arrest Authority'),
('pi24-q10','PI-24',10,'The MJM 2026 Private Detective Accreditation requires completion of how many hours of curriculum under GA Admin Code 509-3-.06?','40 hours','48 hours','72 hours','120 hours','C','GA Admin Code 509-3-.06 mandates a 72-hour PI training curriculum for licensure. The MJM 2026 program is specifically designed to meet and document completion of these 72 required hours.',false,'Compliance');
