-- ============================================================
-- 022_uas_quiz.sql
-- Quiz questions for UAS-01 through UAS-24
-- 5 questions per module (UAS-01–23) + 10 capstone (UAS-24)
-- Total: 125 questions
-- GBPDSA 24-hour unarmed security officer standard
-- ============================================================

DELETE FROM public.quiz_questions WHERE module_id LIKE 'UAS-%';

INSERT INTO public.quiz_questions
  (id, module_id, sequence, question, option_a, option_b, option_c, option_d, correct_answer, explanation, is_critical, topic)
VALUES

-- ============================================================
-- UAS-01: Role & Legal Authority
-- ============================================================
('uas01-q1','UAS-01',1,
 'What is the PRIMARY source of a security officer''s authority to act on private property?',
 'The Georgia POST certification granted by GBPDSA',
 'Peace officer powers delegated by the local sheriff',
 'The property owner''s right to manage their premises and the employment contract with the security agency',
 'The citizen''s arrest statute under OCGA 17-4-60',
 'C',
 'Security officers derive their authority from the property owner''s legal rights and their employment relationship — not from governmental police power. They are private agents, not peace officers.',
 true,'legal-authority'),

('uas01-q2','UAS-01',2,
 'Which of the following actions is WITHIN the lawful authority of a licensed unarmed security officer?',
 'Issuing criminal citations for misdemeanor offenses committed on the property',
 'Requesting a trespassing person to leave and calling law enforcement if they refuse',
 'Conducting a warrantless search of a person''s bag without their consent',
 'Detaining a person indefinitely until the property owner arrives',
 'B',
 'Security officers can request departure and call law enforcement. They cannot issue citations, conduct non-consensual searches, or detain persons indefinitely.',
 false,'legal-authority'),

('uas01-q3','UAS-01',3,
 'A security officer who arrests a person for a misdemeanor offense they did not witness commits which of the following?',
 'A lawful citizen''s arrest under OCGA 17-4-60',
 'An act protected by qualified immunity',
 'A false imprisonment, exposing themselves and the employer to civil liability',
 'A minor procedural violation with no legal consequence',
 'C',
 'OCGA 17-4-60 limits citizen arrest to felonies committed in the officer''s presence. A misdemeanor arrest without that authority constitutes false imprisonment under OCGA 51-7-20.',
 false,'legal-authority'),

('uas01-q4','UAS-01',4,
 'Under the GBPDSA framework, which entity must be licensed in addition to individual security officers?',
 'Each client facility where security services are provided',
 'The employing security agency itself',
 'The property owner who hires the security company',
 'Local law enforcement agencies that coordinate with security',
 'B',
 'OCGA Title 43, Chapter 38 requires both individual security officers and the employing security agency to be licensed by the GBPDSA.',
 false,'licensing'),

('uas01-q5','UAS-01',5,
 'What is the critical distinction between a security officer and a peace officer?',
 'Security officers carry weapons; peace officers do not',
 'Security officers work nights; peace officers work days',
 'Peace officers have governmental authority and can arrest for misdemeanors; security officers are private agents limited to felony citizen arrest',
 'Security officers are licensed by GBPDSA; peace officers are unlicensed',
 'C',
 'The fundamental distinction is governmental authority. Peace officers exercise state power and can arrest for misdemeanors they witness. Security officers are private agents whose arrest authority is limited to felonies in their presence.',
 false,'legal-authority'),

-- ============================================================
-- UAS-02: GBPDSA Framework
-- ============================================================
('uas02-q1','UAS-02',1,
 'Under GA Admin Code 509-3-.01, how many hours of training are required before a security officer may begin unarmed duty in Georgia?',
 '8 hours',
 '16 hours',
 '24 hours',
 '40 hours',
 'C',
 'GA Admin Code 509-3-.01 establishes the 24-hour training requirement for unarmed security officers. This is the regulatory basis for the entire UAS curriculum.',
 true,'licensing'),

('uas02-q2','UAS-02',2,
 'The GBPDSA is empowered to take which enforcement action against a licensee who violates the Code of Conduct?',
 'Criminal prosecution under OCGA Title 16',
 'Suspension or revocation of the individual or agency license',
 'Civil fines only — no license revocation authority',
 'Referral to the Georgia Attorney General only',
 'B',
 'The GBPDSA has authority to suspend or revoke licenses of both individual officers and employing agencies under OCGA Title 43, Chapter 38.',
 false,'licensing'),

('uas02-q3','UAS-02',3,
 'A security officer''s GBPDSA license has lapsed. They continue working for one week before renewing. This officer has:',
 'Committed no offense if they renew within 30 days',
 'Worked without legal authority and may face GBPDSA disciplinary action',
 'Retained full authority because their employer''s agency license is current',
 'Voluntarily suspended their authority only for armed posts',
 'B',
 'Working as a security officer with a lapsed individual license violates OCGA 43-38-10. The agency license does not cover the individual''s expired credentials.',
 false,'licensing'),

('uas02-q4','UAS-02',4,
 'Which document must a security officer carry during every shift and present on request?',
 'Their employment contract with the security agency',
 'A letter of authorization from the client property owner',
 'Their current GBPDSA individual license',
 'Their completed training certificate from the 24-hour course',
 'C',
 'OCGA 43-38-10 requires licensed security officers to carry their GBPDSA license during duty and to display it upon lawful request.',
 false,'licensing'),

('uas02-q5','UAS-02',5,
 'An officer from Florida holds a valid Florida security license. They want to work security in Georgia without obtaining a GBPDSA license. This is:',
 'Permissible if the Florida license is active',
 'Permissible if the Georgia employer verifies the Florida license',
 'Not permissible — Georgia requires its own GBPDSA license for all officers working in-state',
 'Permissible for up to 90 days under interstate reciprocity',
 'C',
 'Georgia requires its own GBPDSA licensure. No automatic reciprocity exists — out-of-state officers must obtain a Georgia license before performing security duties in the state.',
 false,'licensing'),

-- ============================================================
-- UAS-03: Ethics & Professional Conduct
-- ============================================================
('uas03-q1','UAS-03',1,
 'A person you are holding offers you $50 to let them go and not file a report. The correct response is:',
 'Accept the money and release them — minor offenses are not worth the paperwork',
 'Refuse the offer, continue the hold, document the bribery attempt, and report to your supervisor',
 'Refuse the offer but allow them to leave since you lack arrest authority for misdemeanors',
 'Accept the money but still file the incident report',
 'B',
 'Accepting a bribe is a GBPDSA Code of Conduct violation and a criminal offense. The bribery attempt must be documented and reported. The hold continues per post order.',
 true,'ethics'),

('uas03-q2','UAS-03',2,
 'A friend who works in the building asks you to share the access code to the secure server room so they can retrieve a personal item. You should:',
 'Share the code since they are an employee and you know them personally',
 'Share the code only if they show their employee badge',
 'Refuse — access codes are confidential and sharing them violates your confidentiality obligation',
 'Share the code but document that you did so',
 'C',
 'Access codes and security information are client confidential. Sharing them with unauthorized persons — even known employees — violates the GBPDSA Code of Conduct and may constitute a security breach.',
 false,'ethics'),

('uas03-q3','UAS-03',3,
 'You witness a fellow security officer falsifying entries in the patrol log to cover for time they spent off-post. Your ethical and professional obligation is to:',
 'Ignore it — it is not your place to report a colleague',
 'Confront the officer directly and ask them to correct the log',
 'Report the observed misconduct to your supervisor and document what you witnessed',
 'Correct the log yourself to reflect accurate times',
 'C',
 'The GBPDSA Code of Conduct requires reporting witnessed misconduct. Ignoring it makes you complicit; correcting the log without authorization is outside your role. The supervisor is the appropriate reporting channel.',
 true,'ethics'),

('uas03-q4','UAS-03',4,
 'Which of the following is a PROHIBITED conflict of interest for a security officer?',
 'Reporting a theft committed by a member of the public',
 'Using your security position to run a personal investigation for a family member',
 'Maintaining professional relationships with local law enforcement',
 'Reporting security deficiencies to your supervisor',
 'B',
 'Using your security position for personal gain or for the benefit of personal relationships is a conflict of interest prohibited by the GBPDSA Code of Conduct.',
 false,'ethics'),

('uas03-q5','UAS-03',5,
 'A client manager asks you to prepare an incident report that minimizes the severity of an event to avoid bad publicity. You should:',
 'Comply — the client is ultimately your customer',
 'Prepare two reports: one accurate for your files and one altered for the client',
 'Refuse to alter the report — incident reports must reflect factual, objective accounts regardless of client preference',
 'Submit the altered report but note your objection verbally',
 'C',
 'Falsifying or altering an incident report is a GBPDSA Code violation and potentially a criminal offense under OCGA 16-10-94. Professional ethics require accurate documentation over client convenience.',
 false,'ethics'),

-- ============================================================
-- UAS-04: Criminal & Civil Law
-- ============================================================
('uas04-q1','UAS-04',1,
 'Under OCGA Title 16, what is the primary distinction between a felony and a misdemeanor?',
 'Felonies are committed outdoors; misdemeanors indoors',
 'Felonies carry potential imprisonment of more than 12 months; misdemeanors carry 12 months or less',
 'Only felonies can be reported to law enforcement',
 'Misdemeanors are committed against property; felonies against persons',
 'B',
 'Georgia law classifies offenses primarily by maximum incarceration: felonies exceed 12 months (state prison); misdemeanors are 12 months or less (county jail). This distinction determines citizen arrest authority.',
 false,'criminal-law'),

('uas04-q2','UAS-04',2,
 'The merchant protection statute under OCGA 51-7-60 allows a brief detention of a suspected shoplifter IF:',
 'Any employee reports seeing suspicious behavior near merchandise',
 'There is reasonable ground to believe theft occurred, detention is in a reasonable manner, and for a reasonable time only',
 'The person fails to provide identification when asked',
 'The value of merchandise suspected stolen exceeds $500',
 'B',
 'OCGA 51-7-60 provides qualified privilege for detention when: (1) reasonable grounds to believe theft occurred, (2) reasonable manner of detention, (3) reasonable duration. All three must be present.',
 false,'criminal-law'),

('uas04-q3','UAS-04',3,
 'A security officer who uses excessive force during a shoplifting detention may face which consequences?',
 'None — security officers are immune from civil suits while acting in good faith',
 'Only GBPDSA disciplinary action; no criminal exposure',
 'Criminal charges and civil liability to the detainee for the officer and potentially the employer',
 'Civil liability only if the detainee was seriously injured',
 'C',
 'Excessive force can result in criminal assault charges and civil liability. The employer may also be vicariously liable. There is no immunity provision for private security officers using excessive force.',
 false,'civil-liability'),

('uas04-q4','UAS-04',4,
 'The legal concept of respondeat superior means that in a civil lawsuit arising from a security officer''s on-duty conduct:',
 'Only the individual officer can be sued — the employer is shielded',
 'The employer may be held liable for the officer''s actions committed within the scope of employment',
 'The property owner is always the sole defendant',
 'The officer is immune from personal liability if following post orders',
 'B',
 'Respondeat superior holds employers vicariously liable for employees'' on-duty torts. Security officers can be sued personally AND the employing agency can be sued for the officer''s conduct within the scope of employment.',
 true,'civil-liability'),

('uas04-q5','UAS-04',5,
 'A security officer detains a person for 45 minutes based solely on a coworker''s unverified claim that the person looked suspicious near the register. This detention most likely constitutes:',
 'A lawful investigative hold under the merchant protection statute',
 'False imprisonment — no reasonable grounds and excessive duration',
 'A valid citizen''s arrest for suspected shoplifting',
 'A reasonable use of authority protected under GBPDSA licensing',
 'B',
 'False imprisonment requires unlawful restraint. Detaining based on vague suspicion with no articulable basis for an unreasonable duration falls outside the merchant protection statute and constitutes actionable false imprisonment.',
 true,'civil-liability'),

-- ============================================================
-- UAS-05: Laws of Arrest
-- ============================================================
('uas05-q1','UAS-05',1,
 'Under OCGA 17-4-60, a private citizen may make an arrest ONLY when:',
 'Any criminal offense has occurred within the last 24 hours',
 'A misdemeanor is committed in their presence',
 'A felony has been committed and the officer has reasonable grounds to believe the arrested person committed it',
 'They have written authorization from the property owner',
 'C',
 'OCGA 17-4-60 limits citizen arrest to cases where a felony has been committed AND the citizen has reasonable grounds to believe the arrested person committed it. Misdemeanor citizen arrests are not authorized.',
 true,'arrest-authority'),

('uas05-q2','UAS-05',2,
 'A security officer witnesses a patron remove merchandise from a store and conceal it in their clothing inside the store. The patron has not yet exited. The officer''s best course of action is:',
 'Immediately physically restrain the patron',
 'Wait and observe — a theft has not legally occurred until the patron exits',
 'Announce to the patron that they are under arrest',
 'Follow at a safe distance and contact store management per post order before intervening',
 'D',
 'Best practice is to follow post orders — typically wait for exit and contact management — rather than unilateral physical restraint at the concealment stage, which creates legal risk.',
 false,'arrest-authority'),

('uas05-q3','UAS-05',3,
 'The civil tort equivalent of unreasonable seizure by a private security officer is:',
 'Criminal trespass',
 'False imprisonment under OCGA 51-7-20',
 'Battery under OCGA 16-5-23',
 'Conversion under Georgia common law',
 'B',
 'While the Fourth Amendment directly binds government actors, unreasonable restraint by private actors is enforced through civil false imprisonment under OCGA 51-7-20. The practical standard mirrors constitutional reasonableness: reasonable grounds, manner, and duration.',
 false,'arrest-authority'),

('uas05-q4','UAS-05',4,
 'When making a citizen''s arrest for a felony, which of the following is required?',
 'The officer must have a warrant issued by a magistrate',
 'The officer must be in uniform',
 'The officer must use the minimum force necessary and transfer custody to law enforcement promptly',
 'The officer must verbally advise the subject of Miranda rights',
 'C',
 'Citizens making lawful arrests must use minimum necessary force and must promptly transfer custody to law enforcement. Miranda rights are a law enforcement obligation; private citizens are not required to give Miranda warnings.',
 false,'arrest-authority'),

('uas05-q5','UAS-05',5,
 'A person is physically restrained by a security officer based on a coworker''s tip that the person committed theft — the officer did not witness any felony. This physical restraint is:',
 'Lawful if the officer genuinely believed a felony had occurred',
 'Unlawful — the officer lacked the statutory basis for citizen arrest, making the restraint false imprisonment',
 'Lawful because any security officer may physically detain any suspect',
 'Unlawful only if the detainee is injured during the restraint',
 'B',
 'Without the statutory basis under OCGA 17-4-60 (felony committed AND reasonable grounds person committed it, in officer''s presence), the physical restraint has no legal authority and constitutes false imprisonment regardless of good faith belief.',
 true,'arrest-authority'),

-- ============================================================
-- UAS-06: Search & Seizure
-- ============================================================
('uas06-q1','UAS-06',1,
 'A security officer may lawfully search a person''s bag at an access control point when:',
 'The officer has a reasonable suspicion of criminal activity',
 'The person is on private property',
 'The person voluntarily consents to the search as a condition of entry',
 'The property owner has instructed the officer to search all bags',
 'C',
 'Security officers may only search persons or property with voluntary consent. A posted notice that bags are subject to search as a condition of entry — with persons who refuse permitted to leave — creates a lawful consensual search framework.',
 false,'search-seizure'),

('uas06-q2','UAS-06',2,
 'A person consents to a bag search and then says "stop, I revoke my consent" while the officer is mid-search. The officer MUST:',
 'Complete the search since it was started with valid consent',
 'Stop the search immediately — consent can be withdrawn at any time',
 'Complete only the portion of the search already underway before stopping',
 'Call law enforcement before stopping',
 'B',
 'Consent is revocable at any time. A private security officer who continues a search after consent is withdrawn is conducting an unlawful search. The search must stop immediately upon withdrawal.',
 true,'search-seizure'),

('uas06-q3','UAS-06',3,
 'The plain view doctrine means that security officers:',
 'May search anywhere they can see from their post',
 'May note and report items openly visible without conducting a search — no expectation of privacy attaches to items in plain view',
 'May seize any contraband they observe during a lawful search',
 'May photograph anything visible from a public vantage point',
 'B',
 'Items visible in plain view do not require a search to observe. Security officers may note and report what they observe in plain view. Seizure of those items, however, requires law enforcement authority.',
 false,'search-seizure'),

('uas06-q4','UAS-06',4,
 'Law enforcement arrives at a scene where you have observed what appears to be stolen merchandise in plain view. Your role regarding that evidence is:',
 'Photograph and secure the merchandise yourself before officers arrive',
 'Point out the location of the evidence to officers and preserve the scene around it',
 'Remove the merchandise to the security office for safekeeping',
 'Decline to share observations since you are a private actor',
 'B',
 'Your role is to direct law enforcement to the evidence location and maintain scene integrity. Moving evidence — even for safekeeping — can destroy chain of custody and admissibility.',
 false,'evidence-handling'),

('uas06-q5','UAS-06',5,
 'A security officer searches a person''s pockets without consent and finds a weapon. This evidence will most likely:',
 'Be fully admissible because private searches are not subject to the exclusionary rule',
 'Be admissible criminally but the officer faces civil liability for the unlawful search',
 'Be challenged, and the officer and employer face civil liability for the unauthorized search',
 'Be protected under the good faith exception to the Fourth Amendment',
 'C',
 'An unauthorized search by a private security officer creates civil liability for assault and false imprisonment. The officer and employer face exposure regardless of what was found. The evidence may also face admissibility challenges.',
 false,'search-seizure'),

-- ============================================================
-- UAS-07: Use of Force
-- ============================================================
('uas07-q1','UAS-07',1,
 'The use-of-force continuum requires that a security officer''s response be:',
 'Always verbal first, regardless of the nature of the threat',
 'Proportional to the threat level actually faced — not greater than what is needed to address the threat',
 'Escalated to maximum force when any physical contact occurs',
 'Limited to verbal commands only for unarmed officers',
 'B',
 'The use-of-force continuum requires proportionality — the response must match the threat. An unarmed officer is not limited to verbal commands only, but any physical response must match the level of threat actually faced.',
 true,'use-of-force'),

('uas07-q2','UAS-07',2,
 'An imminent threat that justifies physical force means:',
 'The officer believes violence may occur sometime in the future',
 'The threat is immediate, present, and the person has the means and apparent intent to cause harm now',
 'Any person who raises their voice toward the officer',
 'Any person who refuses a verbal command to leave',
 'B',
 'Imminent threat requires: (1) immediacy — happening now; (2) means — the person can actually cause harm; (3) apparent intent — overt actions indicating intent. All three must be present to justify physical force.',
 false,'use-of-force'),

('uas07-q3','UAS-07',3,
 'After any use of physical force, an unarmed security officer''s IMMEDIATE obligations include:',
 'Nothing — documentation can wait until end of shift',
 'Notify a supervisor, call for medical attention if needed, and begin contemporaneous documentation',
 'File a report only if the subject was injured',
 'Await law enforcement direction before documenting anything',
 'B',
 'Post-use-of-force obligations are immediate: (1) medical attention for any injuries, (2) supervisor notification, (3) contemporaneous documentation. Delay reduces accuracy and creates legal exposure.',
 true,'use-of-force'),

('uas07-q4','UAS-07',4,
 'A verbally aggressive person who is shouting but has made no physical movement toward the officer justifies which level of response?',
 'Immediate physical restraint to prevent escalation',
 'Verbal de-escalation — shouting alone does not constitute an imminent physical threat',
 'Call for backup and draw any available defensive tool',
 'Full withdrawal from the scene with no intervention',
 'B',
 'Verbal aggression, absent physical threat or movement, calls for verbal de-escalation — not physical force. Proportionality requires that physical response be reserved for physical threats.',
 false,'use-of-force'),

('uas07-q5','UAS-07',5,
 'A security officer applies physical restraint to control an actively combative person. Once the person stops resisting, the officer MUST:',
 'Maintain the restraint until law enforcement arrives regardless of the subject''s compliance',
 'Reduce force to match the reduced threat — continued application of force beyond what the situation requires becomes excessive',
 'Increase force to ensure the subject cannot resume resistance',
 'Release the subject immediately and withdraw',
 'B',
 'Force must be continuously calibrated to the actual threat level. Once a person stops resisting, the threat level drops and continued force becomes excessive — and potentially criminally and civilly actionable.',
 false,'use-of-force'),

-- ============================================================
-- UAS-08: De-escalation
-- ============================================================
('uas08-q1','UAS-08',1,
 'In the LEAPS de-escalation framework, what does the "L" represent?',
 'Locate the subject',
 'Listen actively — giving the person the opportunity to speak and feel heard',
 'Lock down the area',
 'Level the playing field by matching the subject''s tone',
 'B',
 'LEAPS stands for Listen, Empathize, Ask, Paraphrase, Summarize. Active listening is the foundation — a person who feels heard is significantly less likely to escalate to physical behavior.',
 false,'de-escalation'),

('uas08-q2','UAS-08',2,
 'The concept of proxemics is important in de-escalation because:',
 'Proper spelling of incident reports reduces legal liability',
 'Maintaining appropriate distance reduces the subject''s sense of threat and gives the officer reaction time',
 'Proximity to backup officers improves response time',
 'Standing close to a subject demonstrates authority and reduces defiance',
 'B',
 'Proxemics — the study of personal space — is critical in de-escalation. Standing too close escalates threat perception. A safe distance gives both parties room and gives the officer reaction time if the situation escalates.',
 false,'de-escalation'),

('uas08-q3','UAS-08',3,
 'Which of the following is a recognized pre-attack indicator?',
 'A person who makes sustained eye contact',
 'A person who asks for directions',
 'A person who blades their body, clenches fists, and scans the environment rapidly',
 'A person who speaks loudly but is not using profanity',
 'C',
 'Body blading, fist clenching, and rapid environmental scanning are recognized pre-attack indicators. These are behavioral signals that suggest the person may be preparing for physical action.',
 false,'de-escalation'),

('uas08-q4','UAS-08',4,
 'De-escalation should be abandoned and force considered when:',
 'The subject raises their voice beyond a certain volume',
 'The subject has ignored three verbal commands',
 'The subject''s behavior presents an imminent physical threat that cannot be safely resolved through further verbal engagement',
 'The officer feels personally disrespected by the subject',
 'C',
 'De-escalation is always preferred, but the transition to force is appropriate when the situation becomes an imminent physical threat. Personal disrespect, raised voices, or failure to immediately comply do not alone justify force.',
 true,'de-escalation'),

('uas08-q5','UAS-08',5,
 'An officer''s goal in a de-escalation interaction is:',
 'To win the argument and establish clear authority',
 'To resolve the situation with the minimum level of force necessary — ideally none',
 'To document the encounter for future disciplinary action',
 'To remove the person from the property as quickly as possible',
 'B',
 'De-escalation''s goal is safe resolution with minimum force. The outcome is a stable situation — not a demonstrated authority win, documentation for discipline, or speed of removal.',
 false,'de-escalation'),

-- ============================================================
-- UAS-09: Observation, Patrol & Situational Awareness
-- ============================================================
('uas09-q1','UAS-09',1,
 'The OODA Loop — Observe, Orient, Decide, Act — is applied to security patrol to:',
 'Ensure officers take action before gathering information',
 'Describe a systematic decision-making process that converts environmental information into appropriate responses',
 'Prioritize documentation over situational awareness',
 'Limit officer response to only observed criminal activity',
 'B',
 'The OODA Loop is a decision-making framework: Observe (gather data), Orient (interpret context), Decide (choose response), Act (execute). Applied to patrol, it creates systematic, information-driven responses.',
 false,'situational-awareness'),

('uas09-q2','UAS-09',2,
 'A security officer on patrol establishes a baseline for their patrol area. What does this baseline represent?',
 'The minimum number of patrol cycles required per shift',
 'The normal, expected conditions against which anomalies are measured',
 'The documentation standard for patrol logs',
 'The physical path the officer must walk on each patrol',
 'B',
 'A baseline is the established normal for an environment — typical foot traffic, sound levels, vehicle patterns, occupancy. Anomalies (deviations from baseline) trigger elevated attention. You cannot recognize what is wrong until you know what is normal.',
 false,'situational-awareness'),

('uas09-q3','UAS-09',3,
 'Which patrol methodology provides the most thorough coverage of a large outdoor perimeter?',
 'Fixed post — remaining at a single point of vulnerability',
 'Roving patrol — moving through the entire area on varied, unpredictable routes',
 'Vehicle patrol only — driving the perimeter road without dismounting',
 'Random spot-checking of key locations only',
 'B',
 'Roving patrol with varied routes provides comprehensive coverage and unpredictability — a key deterrence factor. Fixed posts sacrifice coverage range; vehicle-only patrol misses details visible only on foot.',
 false,'patrol-methods'),

('uas09-q4','UAS-09',4,
 'A patrol log entry that reads "0145 — All quiet" is:',
 'Sufficient — it documents the time and status',
 'Insufficient — it provides no specific location, areas checked, or observations that would prove a patrol occurred',
 'Preferred — brief entries reduce administrative burden',
 'Acceptable only for overnight shifts when activity is low',
 'B',
 '"All quiet" entries provide no evidentiary value that a patrol occurred. Effective patrol logs specify: time, location, areas covered, any observations. In litigation, a vague log fails to prove the officer actually patrolled.',
 false,'documentation'),

('uas09-q5','UAS-09',5,
 'You notice a fire door in a stairwell, normally closed and alarmed, is propped open at 0230. Your response should be:',
 'Close the door and continue patrol without logging the incident',
 'Secure the door, document the time/location/condition in your patrol log, and report to your supervisor',
 'Leave the door as found to preserve evidence and call the fire marshal',
 'Note it in your log but take no action until dayshift arrives',
 'B',
 'A propped fire door is both a fire safety violation and an access control failure. Secure it immediately, then document fully and notify your supervisor. Leaving it open creates ongoing risk.',
 false,'patrol-methods'),

-- ============================================================
-- UAS-10: Access Control & Perimeter Security
-- ============================================================
('uas10-q1','UAS-10',1,
 'The principle of layered defense in perimeter security means:',
 'Using only the outermost perimeter fence as the primary security measure',
 'Creating multiple concentric security layers so that defeating one does not grant access to the core',
 'Alternating security personnel between layers on a rotating schedule',
 'Building higher fencing around the entire property',
 'B',
 'Layered defense places multiple security barriers between the public and the protected asset — perimeter fencing, parking area controls, building entry access, and interior access controls. Each layer slows and detects intruders.',
 false,'access-control'),

('uas10-q2','UAS-10',2,
 'Tailgating at an access control point is best prevented by:',
 'Installing taller turnstiles',
 'Requiring one person at a time through controlled entry, with the officer verifying each credential before the door closes',
 'Asking entering persons to stop tailgaters themselves',
 'Installing CCTV cameras pointed at the entrance',
 'B',
 'Tailgating is an access control failure. The solution is procedural: single-entry flow controlled by the officer who verifies each credential before allowing the access point to reset.',
 true,'access-control'),

('uas10-q3','UAS-10',3,
 'A visitor arrives without an appointment and requests access to a secured area. The correct response is:',
 'Grant access if they show a government-issued ID',
 'Deny entry, contact the relevant department to verify their business purpose and obtain authorization, and have them wait in a designated visitor area',
 'Escort them to the secured area and stay with them throughout their visit',
 'Deny entry with no further assistance',
 'B',
 'Unannounced visitors require verification before any access to secured areas. The officer contacts the relevant internal party for authorization; the visitor waits in a controlled area; access is granted only upon confirmed authorization.',
 false,'access-control'),

('uas10-q4','UAS-10',4,
 'A master key to a restricted building is discovered to be missing at end of shift. The officer should:',
 'Search the immediate area and report if not found within 30 minutes',
 'Report the loss immediately to the supervisor — a master key loss is a critical security event requiring immediate escalation',
 'Replace the key from the spare set and note it in the log',
 'Post a notice asking staff if anyone found the key',
 'B',
 'A lost master key is a critical security incident — it may provide unauthorized access to all areas the key covers. Immediate supervisor notification and escalation (potentially rekeying) are required.',
 false,'access-control'),

('uas10-q5','UAS-10',5,
 'Access control logs serve which primary security function beyond granting entry?',
 'They satisfy insurance requirements for the property owner',
 'They create an audit trail showing who accessed which areas and when — enabling post-incident investigation',
 'They provide a daily occupancy count for fire code compliance only',
 'They replace the need for CCTV in low-risk areas',
 'B',
 'Access control logs create accountability and investigative capability. When an incident occurs in a restricted area, logs show who had access and when — enabling investigators to narrow suspects and establish timelines.',
 false,'access-control'),

-- ============================================================
-- UAS-11: Report Writing
-- ============================================================
('uas11-q1','UAS-11',1,
 'The primary reason security incident reports must be written contemporaneously is:',
 'Employers require same-day filing for payroll purposes',
 'Contemporaneous reports are legally more reliable — memory degrades rapidly under stress, and courts recognize immediate documentation as more accurate',
 'Delayed reports are not accepted by law enforcement agencies',
 'Contemporaneous reports allow supervisors to respond to incidents faster',
 'B',
 'Under OCGA 24-8-803 (business records exception), contemporaneous records are presumptively reliable. Memory degrades rapidly under stress. Courts and attorneys scrutinize delayed reports for consistency and reliability.',
 false,'documentation'),

('uas11-q2','UAS-11',2,
 'Which of the following is an example of OBJECTIVE language in an incident report?',
 'Subject appeared intoxicated and hostile',
 'Subject was visibly upset and dangerous',
 'Subject''s speech was slurred, gait was unsteady, and an odor consistent with alcohol was detected within 3 feet',
 'Subject was clearly drunk and looking for a fight',
 'C',
 'Objective language describes observable specifics: slurred speech, unsteady gait, odor. Conclusions like "appeared intoxicated," "dangerous," or "looking for a fight" are subjective and challengeable.',
 false,'documentation'),

('uas11-q3','UAS-11',3,
 'The Five Ws and How framework for incident reports requires that a complete report answer:',
 'Who, What, When, Where, Why, and How',
 'Who, What, When, Where, Witness, and How',
 'What, When, Where, Weapon, Why, and How',
 'Who, Weapon, When, Where, Warning, and How',
 'A',
 'The Five Ws and How — Who, What, When, Where, Why, and How — is the standard structure for complete incident documentation.',
 false,'documentation'),

('uas11-q4','UAS-11',4,
 'After completing an incident report, you realize you made an error on the time of an observation. The correct way to correct it is:',
 'White out the error and write the correct information over it',
 'Discard the report and write a new one',
 'Draw a single line through the error, write the correction adjacent, initial and date it',
 'Leave the error and add a note at the bottom',
 'C',
 'Report corrections must maintain integrity of the original document. Industry and legal standard: single line through the error (so original is still readable), correction adjacent, initialed and dated. White-out destroys the original entry.',
 false,'documentation'),

('uas11-q5','UAS-11',5,
 'A security officer''s incident report may be used in which legal proceedings?',
 'Criminal prosecution only',
 'Civil litigation only',
 'Both criminal and civil proceedings — incident reports are business records with broad evidentiary relevance',
 'Neither — only law enforcement reports are admissible',
 'C',
 'Security incident reports can be introduced in both criminal prosecutions and civil litigation (premises liability, employment disputes, insurance claims). Their accuracy and completeness directly affects all such proceedings.',
 false,'documentation'),

-- ============================================================
-- UAS-12: Emergency Procedures
-- ============================================================
('uas12-q1','UAS-12',1,
 'In an emergency situation, a security officer''s FIRST priority is always:',
 'Preserving the scene for law enforcement investigation',
 'Completing the incident report before memory fades',
 'Life safety — protecting persons from injury and calling for emergency services',
 'Notifying the property owner before taking any action',
 'C',
 'The universal emergency priority hierarchy places life safety first — always. Scene preservation, documentation, and notifications follow. An officer who preserves evidence while a person goes without medical attention has failed their primary duty.',
 true,'emergency-procedures'),

('uas12-q2','UAS-12',2,
 'The RACE acronym used in fire emergency procedures stands for:',
 'Run, Alert, Call, Evacuate',
 'Rescue people in immediate danger, Alarm, Confine fire, Extinguish or Evacuate',
 'Report, Assess, Control, Exit',
 'Respond, Announce, Coordinate, Escape',
 'B',
 'RACE is the standard fire emergency sequence: Rescue persons in immediate danger, Alarm (activate fire alarm and call 911), Confine fire by closing doors, Extinguish if safe to do so or Evacuate.',
 false,'emergency-procedures'),

('uas12-q3','UAS-12',3,
 'A visitor collapses in the lobby and is unresponsive. Before EMS arrives, a security officer trained in CPR/AED should:',
 'Wait for EMS — security officers are not authorized to provide medical assistance',
 'Call 911, begin CPR, and retrieve/deploy the AED if available — continuing until EMS takes over',
 'Move the person to the medical room before beginning assessment',
 'Administer first aid only if the property owner authorizes it in writing',
 'B',
 'Life safety requires immediate response. The security officer should call 911, begin CPR per their training, and use the AED. Waiting without intervention in cardiac arrest dramatically reduces survival.',
 false,'emergency-procedures'),

('uas12-q4','UAS-12',4,
 'During an evacuation, accountability for all persons in the building is achieved by:',
 'Trusting each department to account for their own staff',
 'Checking names off an emergency roster at designated assembly areas and reporting headcount to incident command',
 'Watching the exits to count how many people leave',
 'Using CCTV to review who was in the building at the time of evacuation',
 'B',
 'Accountability requires active headcount at assembly areas matched against occupancy rosters. Exit counting is inaccurate; CCTV review is too slow; departmental self-reporting is uncoordinated.',
 false,'emergency-procedures'),

('uas12-q5','UAS-12',5,
 'A mass casualty incident occurs on your property. Law enforcement and EMS are en route. Your immediate role is:',
 'Begin triage and medical treatment of all casualties',
 'Secure the perimeter, prevent additional persons from entering the danger zone, and direct emergency responders upon arrival',
 'Conduct a full investigation to identify the cause before first responders arrive',
 'Evacuate only the injured and leave others in place',
 'B',
 'In an MCI, the security officer''s pre-arrival role is scene control: prevent additional casualties by keeping bystanders out of the danger zone, and prepare to direct first responders efficiently.',
 true,'emergency-procedures'),

-- ============================================================
-- UAS-13: Terrorism Awareness & SAR
-- ============================================================
('uas13-q1','UAS-13',1,
 'The primary purpose of the national Suspicious Activity Reporting initiative is to:',
 'Allow security officers to arrest suspected terrorists',
 'Create a national reporting channel for behavior-based observations that may indicate terrorist pre-attack activity',
 'Require businesses to report all suspicious persons to the FBI',
 'Replace local law enforcement reporting with federal reporting for all incidents',
 'B',
 'The SAR initiative, established under 6 U.S.C. 1401, creates a national information-sharing network where trained observers can report behavior-based indicators of potential terrorist activity to fusion centers.',
 false,'terrorism-awareness'),

('uas13-q2','UAS-13',2,
 'A SAR report filed by a security officer based primarily on a person''s religion or national origin with no specific behavioral observation is:',
 'Acceptable if the officer had a genuine concern',
 'Required by DHS when persons of certain nationalities are near sensitive facilities',
 'Prohibited — SAR must be based on observed behavior, never protected characteristics',
 'Acceptable if combined with a behavioral observation, however minor',
 'C',
 'DHS SAR Functional Standard v1.5 explicitly prohibits profiling-based reports. SAR must be based entirely on specific, articulable behavior. A report based on religion or national origin violates civil rights law and the SAR program standards.',
 true,'terrorism-awareness'),

('uas13-q3','UAS-13',3,
 'Which of the following is a valid behavioral indicator for a SAR report?',
 'A person wearing a backpack near a government building',
 'A person with a foreign accent asking about public transportation',
 'A person photographing access control panels and guard positions at a water treatment facility on two separate occasions in one day',
 'A person who appears nervous while passing through a checkpoint',
 'C',
 'The two-visit pattern with focused photography of security infrastructure at a critical facility is a specific, articulable behavioral indicator. Wearing a backpack, foreign accents, and checkpoint nervousness are common behaviors with innocent explanations.',
 false,'terrorism-awareness'),

('uas13-q4','UAS-13',4,
 'When a security officer observes suspicious pre-attack activity, their role is to:',
 'Approach and question the subject directly to gather more information',
 'Observe, document, and report — let law enforcement investigate',
 'Follow the subject to their next location to determine their intent',
 'Attempt to identify the subject by photographing them',
 'B',
 'Observe-Document-Report is the security officer''s role. Approaching, following, or photographing subjects escalates the situation and may compromise a law enforcement investigation.',
 false,'terrorism-awareness'),

('uas13-q5','UAS-13',5,
 'The Georgia Information Sharing and Analysis Center (GISAC) is operated by:',
 'The Georgia Department of Homeland Security as an independent agency',
 'The Georgia Bureau of Investigation as the state''s primary fusion center',
 'The Atlanta Police Department for Fulton County incidents only',
 'FEMA as part of the national emergency management system',
 'B',
 'GISAC is the GBI''s fusion center — the state''s primary hub for intelligence sharing across law enforcement, private security, and government agencies. SAR reports flow through local law enforcement to GISAC.',
 false,'terrorism-awareness'),

-- ============================================================
-- UAS-14: Bomb Threats & Suspicious Packages
-- ============================================================
('uas14-q1','UAS-14',1,
 'When receiving a bomb threat call, what is the FIRST action a security officer should take?',
 'Hang up and immediately call 911',
 'Keep the caller on the line as long as possible while signaling a colleague to call 911',
 'Announce the threat over the building PA to initiate evacuation',
 'Verify the threat is credible before taking any action',
 'B',
 'The DHS Bomb Threat Checklist directs: keep the caller on the line to gather maximum information while another person calls 911. Every second of information may help investigators.',
 true,'bomb-threat'),

('uas14-q2','UAS-14',2,
 'At what point is it safe to use a radio or cell phone near a suspicious package?',
 'Immediately — calls to 911 are always safe near suspected devices',
 'Only after the package has been x-rayed',
 'Only outside the minimum standoff distance — RF signals can trigger certain detonators',
 'Any time, because consumer electronics cannot trigger detonators',
 'C',
 'RF signals from radios and cell phones can trigger certain types of improvised explosive devices. No radio or cell phone communication is safe inside the standoff perimeter.',
 false,'bomb-threat'),

('uas14-q3','UAS-14',3,
 'The minimum standoff distance from a small suspicious package (pipe bomb size) is:',
 '15 feet',
 '35 feet',
 '70 feet',
 '150 feet',
 'C',
 'DHS and ATF guidance establishes 70 feet as the minimum standoff for a small suspicious package. Vehicle bombs require 320-500 feet. These are minimums — more distance is always safer.',
 false,'bomb-threat'),

('uas14-q4','UAS-14',4,
 'Which combination of package characteristics is MOST concerning when assessing for suspicious content?',
 'It is wrapped in brown paper and has no return address',
 'It has no return address, an oily stain, excessive postage, and arrived unexpectedly',
 'It is heavier than expected for its size',
 'It has a handwritten address with a misspelled word',
 'B',
 'Multiple criteria present simultaneously dramatically elevate concern. Three or more criteria — oily stain, excessive postage, unexpected arrival, no return address — warrant treating the package as suspicious.',
 false,'bomb-threat'),

('uas14-q5','UAS-14',5,
 'Who has the authority to make the evacuation decision when a bomb threat is received?',
 'Only the local fire marshal',
 'Only law enforcement',
 'The building emergency coordinator or supervisor — or the security officer if no one is reachable and the threat is immediate',
 'Only the property owner',
 'C',
 'Evacuation authority rests with the building emergency coordinator or supervisor. If neither is immediately reachable and the threat is credible and immediate, the security officer must act — evacuate and notify simultaneously.',
 false,'bomb-threat'),

-- ============================================================
-- UAS-15: CPTED
-- ============================================================
('uas15-q1','UAS-15',1,
 'Which CPTED principle is most directly served by trimming landscaping vegetation to below 3 feet near entry points?',
 'Territorial reinforcement',
 'Natural surveillance — removing concealment opportunities restores sight lines',
 'Maintenance — vegetation management is primarily a maintenance function',
 'Natural access control — low vegetation directs foot traffic',
 'B',
 'Natural surveillance requires unobstructed sight lines. Vegetation that exceeds 3 feet provides concealment for criminals approaching entry points. Trimming restores the ability of legitimate users to observe — and be seen in — the space.',
 false,'cpted'),

('uas15-q2','UAS-15',2,
 'An informal foot path worn through landscaping near the building perimeter is a signal of:',
 'Natural surveillance success',
 'Natural access control failure — people are bypassing the controlled entry point',
 'Territorial reinforcement — showing the area is heavily used',
 'Maintenance deficiency — the landscaping needs replanting',
 'B',
 'Informal paths indicate that the intended access control design is being circumvented. People are taking an unauthorized route rather than the controlled entry — an access control failure and a potential vulnerability.',
 false,'cpted'),

('uas15-q3','UAS-15',3,
 'The broken windows theory applied to CPTED maintenance states that:',
 'Windows provide natural surveillance and should never be boarded',
 'Visible signs of neglect and disorder signal that no one cares, inviting escalating criminal activity',
 'Broken windows are only a problem in residential settings',
 'Broken windows must be reported to GBPDSA',
 'B',
 'The broken windows theory holds that visible disorder signals low territorial concern and invites escalating criminal activity. Prompt maintenance — even of minor damage — is a crime prevention measure.',
 false,'cpted'),

('uas15-q4','UAS-15',4,
 'When a security officer identifies a CPTED deficiency during patrol, they should:',
 'Correct it themselves immediately without documentation',
 'Document it in the patrol log with location, nature, risk assessment, and recommended corrective action, then report to supervisor',
 'Note it mentally and include it in their end-of-year review',
 'Photograph it and send to the property owner directly',
 'B',
 'CPTED deficiency reporting requires documentation (location, nature, risk, recommendation) in the patrol log AND supervisor notification. Documentation creates the accountability trail; supervisor notification initiates the repair process.',
 false,'cpted'),

('uas15-q5','UAS-15',5,
 'Which CPTED principle is PRIMARILY served by posting clear, legible signage at all building entry points?',
 'Natural surveillance',
 'Maintenance',
 'Territorial reinforcement — signage signals ownership, rules, and that the space is monitored',
 'Natural access control only',
 'C',
 'Signage reinforces territorial identity — it communicates that this space is owned, has rules, and is monitored. Faded or missing signs remove this signal. This is territorial reinforcement.',
 false,'cpted'),

-- ============================================================
-- UAS-16: Crowd Management
-- ============================================================
('uas16-q1','UAS-16',1,
 'At what crowd density does crush risk begin?',
 '1 person per square meter',
 '2 persons per square meter',
 '4 persons per square meter',
 '8 persons per square meter',
 'C',
 'At 4 persons per square meter, free movement becomes impossible and lateral pressure increases to the point where crushing injuries become possible. Emergency crowd management must begin at this threshold.',
 false,'crowd-management'),

('uas16-q2','UAS-16',2,
 'During emergency egress from an event, the best approach to directing a panicking crowd is:',
 'Place security officers as physical barriers to slow the crowd',
 'Open all exits simultaneously and direct via PA audio — do not add physical barriers to a panicked crowd',
 'Open exits one at a time to control the flow rate',
 'Direct all persons toward a single designated exit for orderly egress',
 'B',
 'In emergency egress, opening all exits maximizes flow capacity and reduces compression. PA audio direction is more effective than physical officer barriers, which add obstruction and potential injury to a panicked crowd.',
 false,'crowd-management'),

('uas16-q3','UAS-16',3,
 'A crowd crush can kill people who are standing upright because:',
 'Falls in dense crowds cause trampling injuries',
 'Lateral compression from the surrounding crowd prevents the diaphragm from expanding — preventing breathing',
 'Body heat in dense crowds causes heat stroke in minutes',
 'People in crowds are more susceptible to cardiovascular events',
 'B',
 'Crowd crush fatalities occur from compressive asphyxia — lateral pressure prevents the chest from expanding for breathing. Victims remain upright because the surrounding crowd holds them up.',
 true,'crowd-management'),

('uas16-q4','UAS-16',4,
 'A security officer working a permitted public assembly event may take which of the following actions?',
 'Arrest any person for any violation of the event''s rules',
 'Direct traffic on the adjacent public street to improve vehicle flow',
 'Deny entry to individuals who violate the event''s code of conduct on private property',
 'Use crowd control barriers to block a public sidewalk adjacent to the event',
 'C',
 'On private property, security officers may enforce the event code of conduct by denying entry. Public street traffic direction requires law enforcement authority; blocking public sidewalks requires municipal permits and law enforcement coordination.',
 false,'crowd-management'),

('uas16-q5','UAS-16',5,
 'The most effective time to intervene in a crowd that is escalating toward dangerous behavior is:',
 'The Active phase, when the behavior is clearly dangerous',
 'The Expressive phase, once emotions are fully engaged',
 'The Casual or Aware phase — early intervention is most effective before the crowd emotionally engages',
 'After law enforcement has been called and is en route',
 'C',
 'Crowd behavior phases (Casual, Aware, Expressive, Active) escalate rapidly. Intervention is most effective and least dangerous in the Casual or Aware phase. Once Active, intervention becomes significantly more dangerous and less effective.',
 false,'crowd-management'),

-- ============================================================
-- UAS-17: Workplace Violence Prevention
-- ============================================================
('uas17-q1','UAS-17',1,
 'Which Type of workplace violence involves a person with no relationship to the workplace?',
 'Type II — Customer/Client',
 'Type I — Criminal Intent',
 'Type III — Worker-on-Worker',
 'Type IV — Personal Relationship',
 'B',
 'Type I (Criminal Intent) involves perpetrators with no legitimate workplace relationship — robbery, theft with violence.',
 false,'workplace-violence'),

('uas17-q2','UAS-17',2,
 'Research from the FBI and Secret Service shows that serious workplace violence is:',
 'Random and impossible to predict',
 'Almost always impulsive with no warning signs',
 'Typically preceded by a pathway from grievance to planning to attack — with observable warning signs along the way',
 'Primarily driven by mental illness rather than behavioral escalation',
 'C',
 'The most consistent research finding on targeted workplace violence is that it is NOT impulsive. It follows a pathway: grievance, ideation, planning, attack. Observable warning signs appear at multiple points. Early reporting can interrupt this pathway.',
 true,'workplace-violence'),

('uas17-q3','UAS-17',3,
 'A security officer''s primary role when they observe a behavioral warning sign is to:',
 'Confront the co-worker directly to assess the seriousness of the threat',
 'Observe, document the specific behavior with date/time/location, and report to supervisor immediately',
 'Wait to see if the behavior continues before involving supervisors',
 'Discuss their concern with other security officers to build consensus before reporting',
 'B',
 'The security officer''s role is observe-document-report. Confronting the subject may escalate. Waiting allows the pathway to continue. Building consensus with colleagues is not the right channel — the supervisor and BTAT are.',
 false,'workplace-violence'),

('uas17-q4','UAS-17',4,
 'In the Run-Hide-Fight protocol, Fight is the appropriate response when:',
 'The officer feels threatened by any subject',
 'Three verbal warnings have been issued',
 'Running and hiding are not possible and the officer''s life is in immediate danger',
 'The officer has a defensive weapon available',
 'C',
 'Fight is an absolute last resort — only when evacuation and sheltering are both impossible and the officer faces imminent life-threatening danger.',
 false,'workplace-violence'),

('uas17-q5','UAS-17',5,
 'When law enforcement officers arrive at an active shooter scene, a security officer should:',
 'Identify themselves loudly and guide officers to the suspect''s last known location',
 'Keep hands visible, drop any weapon, comply with officer instructions immediately, and do not impede their movement',
 'Continue engaging the threat until officers can take over',
 'Brief officers on the layout before following their instructions',
 'B',
 'Law enforcement arriving at an active scene cannot distinguish security officers from threats. Hands must be visible, weapons dropped, and officer instructions followed immediately without hesitation.',
 false,'workplace-violence'),

-- ============================================================
-- UAS-18: Incident Response & Scene Management
-- ============================================================
('uas18-q1','UAS-18',1,
 'When a security officer arrives at a scene with an injured person and potential evidence, their FIRST action should be:',
 'Photograph the scene before anything is disturbed',
 'Establish a scene perimeter to preserve evidence',
 'Assess life safety needs and call for emergency services if needed',
 'Identify and separate witnesses',
 'C',
 'Life safety is always the first priority — always. Injured persons needing medical attention take precedence over scene preservation, witness separation, and documentation.',
 false,'incident-response'),

('uas18-q2','UAS-18',2,
 'Witnesses at an incident scene should be separated immediately because:',
 'It is easier to take their contact information one at a time',
 'Contact between witnesses contaminates their independent accounts — cross-pollinated testimony loses evidentiary value',
 'Witnesses may become violent if allowed to discuss the incident together',
 'Law enforcement requires witness separation as a procedural requirement',
 'B',
 'Memory is highly susceptible to suggestion. Witnesses who discuss an incident together begin incorporating each other''s details into their own accounts. Separated witnesses provide independent evidence.',
 false,'incident-response'),

('uas18-q3','UAS-18',3,
 'A security officer who moves a piece of evidence for safekeeping before law enforcement arrives has:',
 'Acted appropriately to protect the evidence from contamination',
 'Potentially compromised chain of custody and evidentiary value — and may have committed evidence tampering under OCGA 16-10-94',
 'Fulfilled their duty of care to the property owner',
 'Created no legal issue because they are not a law enforcement officer',
 'B',
 'Moving evidence without authority disrupts chain of custody — a legal requirement for evidence admissibility. It can also constitute tampering under OCGA 16-10-94.',
 false,'incident-response'),

('uas18-q4','UAS-18',4,
 'When law enforcement arrives and takes control of the scene, the security officer should:',
 'Return to their post immediately',
 'Meet officers at the perimeter, provide a verbal summary, share contemporaneous notes, disclose anything touched or moved, and remain available',
 'Step back inside the perimeter to continue monitoring the scene',
 'Release all witnesses before handing off to law enforcement',
 'B',
 'The handoff to law enforcement requires: meeting at perimeter, verbal briefing, sharing notes, disclosing all scene disturbances. The officer remains available for follow-up. Releasing witnesses before law enforcement contacts them destroys their evidentiary availability.',
 true,'incident-response'),

('uas18-q5','UAS-18',5,
 'CCTV footage showing the period around an incident must be:',
 'Downloaded by law enforcement only — security officers should not access it',
 'Preserved immediately by notifying IT to prevent overwrite — footage that overwrites before law enforcement copies it may constitute evidence destruction',
 'Automatically preserved by the security system for 90 days',
 'Shared only after a subpoena is received',
 'B',
 'CCTV systems overwrite continuously. If not flagged for preservation, critical footage can be lost within hours. The security officer must notify IT immediately to lock the relevant time window.',
 false,'incident-response'),

-- ============================================================
-- UAS-19: Communications
-- ============================================================
('uas19-q1','UAS-19',1,
 'The NATO phonetic word for the letter P is:',
 'Pacific',
 'Phantom',
 'Papa',
 'Phoenix',
 'C',
 'Papa is the NATO phonetic alphabet word for P. The NATO alphabet provides an unambiguous verbal representation of each letter — critical in radio communications where letter confusion can cause errors.',
 false,'radio-communications'),

('uas19-q2','UAS-19',2,
 'A security officer ends a radio transmission with "Over." This indicates:',
 'The transmission is complete and no response is expected',
 'The transmission is complete and a response is expected from the other party',
 'An emergency requiring all other traffic to clear the channel',
 'The officer is switching to a secondary channel',
 'B',
 '"Over" means the transmission is complete and the officer is waiting for a response. "Out" means the transmission is complete and no response is expected. "Over and Out" is a contradictory phrase and should never be used.',
 false,'radio-communications'),

('uas19-q3','UAS-19',3,
 'FEMA NIMS requires which communication standard during multi-agency emergency response?',
 '10-codes standardized nationally',
 'Plain language — to eliminate code ambiguity across agencies',
 'Military brevity codes for all tactical communications',
 'Agency-specific codes as long as a translator is available',
 'B',
 'NIMS mandates plain language for all emergency communications. 10-codes are not nationally standardized and have caused life-threatening misunderstandings during multi-agency responses.',
 false,'radio-communications'),

('uas19-q4','UAS-19',4,
 'A patrol log entry showing "0230 — All Clear, Post 3" is problematic because:',
 'It is too brief to demonstrate that a patrol actually occurred in any specific area',
 'The time format should be 12-hour, not military',
 'Post designations should not appear in patrol logs',
 'It does not include the officer''s employee number',
 'A',
 '"All Clear" entries without specific locations and areas covered fail to document what was actually observed or where the officer was. In litigation, such logs cannot prove a patrol was conducted.',
 false,'documentation'),

('uas19-q5','UAS-19',5,
 'A security officer discovers their radio is missing at the start of patrol. They should:',
 'Complete the patrol using a personal cell phone as backup',
 'Report the missing radio to the supervisor immediately — a radio in unauthorized hands is a security breach',
 'Borrow a fellow officer''s spare radio without logging it',
 'Wait until the next shift to check if the previous officer left it',
 'B',
 'A missing radio is a security incident — it may be in unauthorized hands, providing access to security communications. Immediate reporting allows the agency to assess the breach and take action.',
 false,'radio-communications'),

-- ============================================================
-- UAS-20: Trespass & Banning
-- ============================================================
('uas20-q1','UAS-20',1,
 'Under OCGA 16-7-21, a person commits criminal trespass by remaining on private property after receiving notice to depart from:',
 'Any person on the property',
 'Only a sworn law enforcement officer',
 'The owner or an authorized agent, which includes security officers',
 'Only the property owner in person',
 'C',
 'OCGA 16-7-21(b)(3) states the notice may come from the owner or authorized agent. Licensed security officers acting within their employment are authorized agents — their notice to depart carries the same legal weight as the owner''s.',
 false,'trespass'),

('uas20-q2','UAS-20',2,
 'Criminal trespass under OCGA 16-7-21 is classified as:',
 'A felony requiring state prison',
 'A misdemeanor',
 'A civil offense only',
 'A federal offense when on federally contracted property',
 'B',
 'Criminal trespass under OCGA 16-7-21 is a misdemeanor. This means security officers cannot make a citizen''s arrest for it — only law enforcement can. The security officer''s role is to issue notice, request departure, and call law enforcement if the person refuses.',
 false,'trespass'),

('uas20-q3','UAS-20',3,
 'A property manager directs a security officer to ban all persons of a specific nationality from the shopping center. The officer should:',
 'Execute the order — the property owner has authority to exclude anyone',
 'Execute the order but document their objection',
 'Refuse to execute the order and report it to their supervisor — banning based on national origin violates 42 U.S.C. 2000a and civil rights law',
 'Execute the order only if the property manager provides written authorization',
 'C',
 'Title II of the Civil Rights Act prohibits businesses open to the public from discriminating based on national origin. A security officer who executes a discriminatory banning order is personally liable alongside the property owner.',
 true,'trespass'),

('uas20-q4','UAS-20',4,
 'A banned individual refuses to leave after being given a verbal trespass notice. The security officer''s next step is:',
 'Physically restrain the individual and hold them for law enforcement',
 'Call law enforcement — criminal trespass is a misdemeanor and the officer lacks arrest authority',
 'Issue a written notice and give them additional time to comply',
 'Escort them forcibly to the exit',
 'B',
 'Physical restraint for a misdemeanor trespass is outside the security officer''s citizen arrest authority. The correct step after a refused verbal notice is to call law enforcement, who have authority to arrest for the misdemeanor.',
 false,'trespass'),

('uas20-q5','UAS-20',5,
 'The primary purpose of maintaining a written ban log is:',
 'Satisfying insurance requirements for the property',
 'Allowing all security officers on any shift to enforce the ban and creating documentation for potential trespass prosecution',
 'Documenting the property owner''s liability protection',
 'Providing GBPDSA with required activity reporting',
 'B',
 'A ban log creates operational continuity — any officer, any shift, can recognize and act on a ban. It also creates the evidentiary record necessary to support a criminal trespass prosecution when the banned individual returns.',
 false,'trespass'),

-- ============================================================
-- UAS-21: Traffic Control & Parking
-- ============================================================
('uas21-q1','UAS-21',1,
 'OCGA 40-6-2 limits the authority to direct traffic on public roadways to:',
 'Any uniformed security officer',
 'Peace officers and authorized traffic control personnel only',
 'Any person with a valid driver''s license',
 'Security officers with a traffic control endorsement on their GBPDSA license',
 'B',
 'OCGA 40-6-2 authorizes only peace officers and officially designated traffic control personnel to direct traffic on public roadways. Private security officers lack this authority on public streets.',
 false,'traffic-control'),

('uas21-q2','UAS-21',2,
 'The ANSI/ISEA 107 Class 2 high-visibility vest requirement applies when:',
 'Directing traffic inside a parking garage only',
 'Working any outdoor security post regardless of traffic proximity',
 'Directing traffic adjacent to roadways where vehicle speeds and traffic volumes require enhanced visibility',
 'Only when directing traffic after dark',
 'C',
 'ANSI/ISEA 107 Class 2 is the minimum for traffic control adjacent to roadways. The standard accounts for vehicle speeds, traffic volume, and worker exposure.',
 false,'traffic-control'),

('uas21-q3','UAS-21',3,
 'A vehicle is parked in a marked fire lane. The security officer''s FIRST action should be:',
 'Immediately call for a tow truck',
 'Issue a parking violation notice and log the violation',
 'Attempt to locate the driver for immediate voluntary relocation before escalating',
 'Leave it for law enforcement to handle',
 'C',
 'Fire lane violations are life-safety issues, but best practice is to attempt to locate the driver first for voluntary compliance — fastest resolution with least disruption. If the driver cannot be located promptly, proceed to violation notice and towing per post order.',
 false,'parking'),

('uas21-q4','UAS-21',4,
 'Towing a vehicle from private property without complying with OCGA 44-1-13 exposes:',
 'Only the towing company to liability',
 'The property owner and potentially the security agency to civil liability from the vehicle owner',
 'No liability — private property towing does not require signage',
 'Only GBPDSA disciplinary action for the security officer',
 'B',
 'OCGA 44-1-13 requires proper signage and a registered towing company. Non-compliant towing can result in the vehicle owner recovering the tow fee and storage charges — and potentially civil liability for conversion.',
 false,'parking'),

('uas21-q5','UAS-21',5,
 'An unauthorized vehicle is parked in a designated accessible parking space. The security officer should:',
 'Issue their own parking citation and tow the vehicle',
 'Call law enforcement — ADA accessible space violations under OCGA 40-6-226 require a peace officer to issue citations',
 'Place a notice on the windshield and move on',
 'Tow the vehicle without notice since ADA violations are strict liability',
 'B',
 'ADA accessible parking violations are statutory offenses under OCGA 40-6-226. Only peace officers can issue citations for statutory violations. The security officer''s role is to document and call law enforcement.',
 false,'parking'),

-- ============================================================
-- UAS-22: Drug & Alcohol Awareness
-- ============================================================
('uas22-q1','UAS-22',1,
 'A person on your property exhibits pinpoint pupils, shallow breathing, pale skin, and is unresponsive. Your first action should be:',
 'Move them to the security office for monitoring',
 'Call 911 immediately — these are signs of opioid overdose, a life-threatening emergency',
 'Administer water and monitor for 10 minutes',
 'Locate their identification and contact their emergency contact',
 'B',
 'Pinpoint pupils, shallow breathing, pale skin, and unresponsiveness are classic opioid overdose indicators — a life-threatening emergency. Call 911 immediately.',
 false,'impairment'),

('uas22-q2','UAS-22',2,
 'You observe an employee who appears impaired. The correct reporting chain is:',
 'Confront the employee directly in front of their colleagues',
 'Report discreetly to your supervisor — management and HR make the fitness-for-duty determination',
 'Report directly to the employee''s manager over the public address system',
 'File a report with GBPDSA as a drug-free workplace violation',
 'B',
 'Employee impairment is a sensitive HR matter. The security officer observes and reports privately to their supervisor. Management and HR make the fitness-for-duty call.',
 false,'impairment'),

('uas22-q3','UAS-22',3,
 'Under OCGA 34-9-415, a security officer who begins a shift while impaired has:',
 'Violated workplace policy only — no personal legal exposure',
 'Violated the drug-free workplace requirement and may face GBPDSA license action, termination, and personal civil liability for any incident on their watch',
 'Only violated their employment contract with the security agency',
 'Done nothing wrong if their employer does not test for drugs',
 'B',
 'Working while impaired in a safety-sensitive role violates OCGA 34-9-415, exposes the officer to GBPDSA disciplinary action including license revocation, and creates personal civil liability for any harm they fail to prevent.',
 false,'impairment'),

('uas22-q4','UAS-22',4,
 'An incident report describing an impaired person as "appeared drunk" is problematic because:',
 'It reveals confidential medical information',
 'It is a subjective conclusion rather than an objective observation — challengeable in any proceeding',
 'It uses a colloquial term instead of a clinical one',
 'It implies the officer performed a field sobriety test they are not certified to conduct',
 'B',
 '"Appeared drunk" is a subjective conclusion. Effective documentation describes specific observations: odor of alcohol, slurred speech, unsteady gait, glazed eyes. These observable facts are far more defensible in legal proceedings.',
 false,'documentation'),

('uas22-q5','UAS-22',5,
 'A person who appears impaired attempts to drive their vehicle out of your property. You should:',
 'Allow them to leave — you cannot legally prevent a person from driving',
 'Notify your supervisor and call law enforcement — do not allow a visibly impaired driver to leave if you can safely prevent it',
 'Physically block their vehicle from exiting',
 'Take their keys and hold them until they are sober',
 'B',
 'Allowing a visibly impaired driver to leave creates potential civil liability. Notify supervisor and call law enforcement. You cannot physically block the vehicle or take keys without legal authority — but you can and should call law enforcement.',
 false,'impairment'),

-- ============================================================
-- UAS-23: Customer Service & Professional Image
-- ============================================================
('uas23-q1','UAS-23',1,
 'The most effective deterrence against opportunistic crime at a facility is:',
 'Aggressive patrol behavior that demonstrates force readiness',
 'A visible, professional, alert security presence that signals competent monitoring',
 'High-profile security technology visible to all visitors',
 'Posting signs warning of prosecution for any violation',
 'B',
 'Research consistently shows that the perception of professional, alert monitoring deters opportunistic crime more than reactive enforcement. A professional officer communicates that the facility is watched and cared about.',
 false,'professional-conduct'),

('uas23-q2','UAS-23',2,
 'OCGA 43-38-10 requires a licensed security officer to:',
 'Carry their GBPDSA license and display it upon lawful request during duty',
 'Wear their license badge on the outside of their uniform at all times',
 'File their license number with the client property owner before each shift',
 'Display their license only when requested by law enforcement',
 'A',
 'OCGA 43-38-10 requires active licensees to carry their license during duty and to display it when lawfully requested.',
 false,'licensing'),

('uas23-q3','UAS-23',3,
 'When handling a complaint from a member of the public about a security incident, the officer should:',
 'Defend their actions and explain why they were correct',
 'Accept the complaint professionally and route it to the supervisor — the officer does not have authority to adjudicate complaints about their own conduct',
 'Refer the complainant to the GBPDSA',
 'Offer to revise the incident report to address the complainant''s concerns',
 'B',
 'Complaints about an officer''s conduct must go to the supervisor. The officer cannot be the judge of their own conduct. Revising the report to satisfy a complainant is a documentation integrity violation.',
 false,'professional-conduct'),

('uas23-q4','UAS-23',4,
 'A security officer who abandons their post without relief has potentially violated:',
 'Only their employment terms — no regulatory consequence',
 'GBPDSA professional conduct standards, their employer''s post orders, and created legal exposure for any incident during the unmanned period',
 'Only OSHA regulations regarding shift coverage',
 'Nothing — officers are permitted to leave when their shift ends regardless of relief',
 'B',
 'Post abandonment violates the GBPDSA Code of Conduct, the employing agency''s post orders, and creates liability exposure for any incident occurring while the post was unmanned.',
 false,'professional-conduct'),

('uas23-q5','UAS-23',5,
 'The primary reason security contract loss most often occurs due to officer conduct is:',
 'Security pricing is set by state regulation and cannot be bid differently',
 'Clients tolerate price differences but not conduct failures that create liability exposure or reputational harm',
 'Officers negotiate contracts directly with clients',
 'Price is irrelevant in security contracting',
 'B',
 'Security clients can absorb moderate price variations but cannot absorb incidents caused by unprofessional conduct — which create liability, reputational harm, and operational disruption.',
 false,'professional-conduct'),

-- ============================================================
-- UAS-24: Final Accreditation Examination (10 capstone questions)
-- ============================================================
('uas24-q1','UAS-24',1,
 'A security officer witnesses a person commit assault — a felony — on another person in the parking lot. Under OCGA 17-4-60, the officer:',
 'Must call law enforcement and may not act',
 'May make a citizen''s arrest because a felony occurred in their presence',
 'May arrest only if they are also a law enforcement officer',
 'May arrest only if authorized in writing by the property owner',
 'B',
 'OCGA 17-4-60 authorizes citizen arrest when a felony has been committed and the citizen has reasonable grounds to believe the arrested person committed it. Witnessed felony assault meets both criteria.',
 false,'legal-authority'),

('uas24-q2','UAS-24',2,
 'Which CPTED principle is MOST directly addressed by replacing burned-out lights in a parking garage?',
 'Territorial reinforcement',
 'Natural surveillance — restored lighting improves sight lines and the perception of monitoring',
 'Natural access control',
 'Maintenance only — lighting is not a CPTED principle',
 'B',
 'Lighting directly supports natural surveillance by enabling legitimate users to see and be seen. It is both a maintenance function and a natural surveillance improvement — the most consequential CPTED correction in a parking environment.',
 false,'cpted'),

('uas24-q3','UAS-24',3,
 'An unarmed security officer is confronted by a person who is verbally threatening but has made no physical movement. Physical force at this moment would be:',
 'Justified under the use-of-force continuum because verbal threats are sufficient',
 'Unjustified — verbal threats alone without imminent physical threat do not authorize physical force',
 'Justified if the officer perceives a threat, regardless of physical action by the subject',
 'Justified once the subject has issued three verbal threats',
 'B',
 'Imminent threat requires immediacy, means, and apparent intent through physical action. Verbal threats alone without physical movement indicating imminent attack do not meet the standard. Physical force at this stage would be excessive.',
 true,'use-of-force'),

('uas24-q4','UAS-24',4,
 'A suspicious package is found at the building entrance. The minimum standoff distance has been established and law enforcement notified. The officer''s next priority is:',
 'Move the package to a safer location away from the building',
 'Maintain the perimeter and prevent anyone from entering until EOD arrives',
 'X-ray the package using building mailroom equipment',
 'Open the package carefully to assess whether it is real',
 'B',
 'Once standoff is established and law enforcement notified, the security officer''s role is perimeter control — keeping everyone outside the standoff zone until EOD professionals assess and clear the package.',
 false,'bomb-threat'),

('uas24-q5','UAS-24',5,
 'When a security officer issues a trespass notice and the person refuses to leave, the officer should:',
 'Physically remove the person from the property',
 'Call law enforcement — the person has committed criminal trespass and law enforcement has arrest authority for misdemeanors',
 'Issue a second written notice and wait for compliance',
 'Detain the person until a supervisor arrives',
 'B',
 'After a valid trespass notice and refusal to depart, criminal trespass under OCGA 16-7-21(b)(3) has occurred. The security officer cannot arrest for a misdemeanor — law enforcement must be called.',
 false,'trespass'),

('uas24-q6','UAS-24',6,
 'Which characteristic makes an incident report most legally defensible?',
 'It was typed and formatted professionally',
 'It was written at end of shift from the officer''s memory',
 'It was written contemporaneously, in objective language, with specific times and locations',
 'It was reviewed and approved by the client property manager',
 'C',
 'Contemporaneous documentation, objective language, and specificity are the three markers of a legally reliable incident report under OCGA 24-8-803.',
 false,'documentation'),

('uas24-q7','UAS-24',7,
 'The life-safety priority hierarchy at an emergency scene places which action FIRST?',
 'Notify the property owner',
 'Preserve the scene for law enforcement',
 'Address injured persons and call for emergency services',
 'Complete the incident report',
 'C',
 'Life safety is always the first priority — injured persons, medical emergencies, and calling for emergency services come before any other action.',
 true,'emergency-procedures'),

('uas24-q8','UAS-24',8,
 'You observe suspicious activity that may indicate terrorist pre-attack surveillance. Under SAR guidelines, your report must be based on:',
 'Your intuition and general knowledge of security threats',
 'The subject''s appearance and country of origin',
 'Specific, articulable behaviors observed — not appearance, race, religion, or national origin',
 'Any behavior that makes you uncomfortable',
 'C',
 'DHS SAR standards require behavioral specificity. Reports based on appearance, race, ethnicity, religion, or national origin are prohibited.',
 false,'terrorism-awareness'),

('uas24-q9','UAS-24',9,
 'The GBPDSA Code of Conduct confidentiality obligation requires security officers to:',
 'Keep all security information secret even from law enforcement upon request',
 'Protect client and operational security information from unauthorized disclosure to uninvolved colleagues and third parties',
 'Share security information only with persons who present a government ID',
 'Disclose security information to any person who appears to have a legitimate need',
 'B',
 'The confidentiality obligation protects client information, operational procedures, and sensitive security details from unauthorized disclosure. It does not obstruct law enforcement, but it does prevent casual sharing with uninvolved colleagues or the public.',
 true,'ethics'),

('uas24-q10','UAS-24',10,
 'A security officer who completes the UAS 24-hour training and passes this examination has satisfied:',
 'The requirement for armed security officer licensing in Georgia',
 'The GBPDSA training prerequisite for unarmed security officer registration under GA Admin Code 509-3-.01',
 'All requirements for a Georgia private detective license',
 'Federal security officer certification requirements',
 'B',
 'GA Admin Code 509-3-.01 establishes the 24-hour training requirement for unarmed security officers. This examination satisfies the training prerequisite — but the license application must still be submitted and approved by GBPDSA.',
 false,'licensing');
