-- Migration: 028_corrective_action
-- Replaces the 24-hour critical-fail lockout with a learner-released corrective
-- action gate. See docs/superpowers/specs/2026-09-08-corrective-action-gate-design.md
--
-- MUST be applied BEFORE the application code deploys. The gate's degradation path
-- depends on remediation_slide_id existing and on slides carrying slideId; deploying
-- code first drops every released learner onto the degraded path at once.

-- ── 1. Stable slide ids ─────────────────────────────────────────────────────
-- Slides live as a JSONB array addressed only by index, which shifts when content is
-- edited. Stamp a stable id derived from the current position so a question can point
-- at the slide that teaches it. Idempotent: slides already carrying a slideId are
-- left untouched.
UPDATE module_lessons ml
SET slides = sub.rebuilt
FROM (
  SELECT
    m.module_id,
    jsonb_agg(
      CASE
        WHEN s.value ? 'slideId' THEN s.value
        ELSE s.value || jsonb_build_object(
          'slideId', m.module_id || '-s' || lpad((s.ordinality - 1)::text, 2, '0')
        )
      END
      ORDER BY s.ordinality
    ) AS rebuilt
  FROM module_lessons m,
       LATERAL jsonb_array_elements(m.slides) WITH ORDINALITY AS s(value, ordinality)
  GROUP BY m.module_id
) sub
WHERE ml.module_id = sub.module_id;

-- ── 2. Question -> slide anchor ─────────────────────────────────────────────
-- Nullable and cross-module: the value is a fully-qualified slide id such as
-- 'PI-05-s00', which may belong to an EARLIER module in the same track. A capstone
-- question is taught upstream, so restricting anchors to the question's own module
-- forces NULL on the highest-stakes questions. NULL degrades to a module-overview
-- link and must never block a learner.
ALTER TABLE quiz_questions ADD COLUMN IF NOT EXISTS remediation_slide_id TEXT;

-- >>> ANCHORS BEGIN
-- Generated by scripts/apply-remediation-anchors.mjs — do not edit by hand.
-- 65 of 65 critical questions anchored; 0 ship unanchored
-- and degrade to a module-overview link. 7 anchors cross modules.
UPDATE quiz_questions SET remediation_slide_id = 'MOD-10-s01' WHERE id = 'mod-10-q2';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-11-s02' WHERE id = 'mod-11-q3';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-12-s01' WHERE id = 'mod-12-q2';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-13-s01' WHERE id = 'mod-13-q2';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-14-s02' WHERE id = 'mod-14-q3';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-15-s00' WHERE id = 'mod-15-q1';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-16-s01' WHERE id = 'mod-16-q2';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-01-s00' WHERE id = 'mod01-q1';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-01-s00' WHERE id = 'mod01-q3';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-02-s03' WHERE id = 'mod02-q1';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-02-s01' WHERE id = 'mod02-q4';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-02-s03' WHERE id = 'mod02-q5';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-03-s01' WHERE id = 'mod03-q2';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-03-s02' WHERE id = 'mod03-q3';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-03-s00' WHERE id = 'mod03-q4';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-07-s02' WHERE id = 'mod07-q1';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-07-s00' WHERE id = 'mod07-q2';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-07-s02' WHERE id = 'mod07-q3';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-07-s06' WHERE id = 'mod07-q5';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-09-s04' WHERE id = 'mod09-q3';
UPDATE quiz_questions SET remediation_slide_id = 'MOD-09-s04' WHERE id = 'mod09-q4';
UPDATE quiz_questions SET remediation_slide_id = 'PI-01-s01' WHERE id = 'pi01-q1';
UPDATE quiz_questions SET remediation_slide_id = 'PI-02-s03' WHERE id = 'pi02-q1';
UPDATE quiz_questions SET remediation_slide_id = 'PI-02-s00' WHERE id = 'pi02-q3';
UPDATE quiz_questions SET remediation_slide_id = 'PI-04-s05' WHERE id = 'pi04-q4';
UPDATE quiz_questions SET remediation_slide_id = 'PI-04-s04' WHERE id = 'pi04-q5';
UPDATE quiz_questions SET remediation_slide_id = 'PI-05-s00' WHERE id = 'pi05-q1';
UPDATE quiz_questions SET remediation_slide_id = 'PI-05-s04' WHERE id = 'pi05-q5';
UPDATE quiz_questions SET remediation_slide_id = 'PI-06-s03' WHERE id = 'pi06-q2';
UPDATE quiz_questions SET remediation_slide_id = 'PI-08-s03' WHERE id = 'pi08-q4';
UPDATE quiz_questions SET remediation_slide_id = 'PI-09-s01' WHERE id = 'pi09-q2';
UPDATE quiz_questions SET remediation_slide_id = 'PI-10-s02' WHERE id = 'pi10-q3';
UPDATE quiz_questions SET remediation_slide_id = 'PI-11-s01' WHERE id = 'pi11-q2';
UPDATE quiz_questions SET remediation_slide_id = 'PI-11-s04' WHERE id = 'pi11-q5';
UPDATE quiz_questions SET remediation_slide_id = 'PI-14-s02' WHERE id = 'pi14-q3';
UPDATE quiz_questions SET remediation_slide_id = 'PI-15-s03' WHERE id = 'pi15-q4';
UPDATE quiz_questions SET remediation_slide_id = 'PI-18-s01' WHERE id = 'pi18-q2';
UPDATE quiz_questions SET remediation_slide_id = 'PI-19-s01' WHERE id = 'pi19-q2';
UPDATE quiz_questions SET remediation_slide_id = 'PI-21-s03' WHERE id = 'pi24-q3';
UPDATE quiz_questions SET remediation_slide_id = 'PI-15-s03' WHERE id = 'pi24-q7';
UPDATE quiz_questions SET remediation_slide_id = 'PI-05-s00' WHERE id = 'pi24-q9';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-01-s00' WHERE id = 'uas01-q1';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-02-s01' WHERE id = 'uas02-q1';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-03-s03' WHERE id = 'uas03-q1';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-03-s00' WHERE id = 'uas03-q3';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-04-s02' WHERE id = 'uas04-q4';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-04-s03' WHERE id = 'uas04-q5';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-05-s00' WHERE id = 'uas05-q1';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-05-s00' WHERE id = 'uas05-q5';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-06-s01' WHERE id = 'uas06-q2';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-07-s00' WHERE id = 'uas07-q1';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-07-s05' WHERE id = 'uas07-q3';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-07-s01' WHERE id = 'uas08-q4';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-10-s02' WHERE id = 'uas10-q2';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-12-s00' WHERE id = 'uas12-q1';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-12-s00' WHERE id = 'uas12-q5';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-13-s03' WHERE id = 'uas13-q2';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-14-s01' WHERE id = 'uas14-q1';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-16-s01' WHERE id = 'uas16-q3';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-17-s01' WHERE id = 'uas17-q2';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-18-s03' WHERE id = 'uas18-q4';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-20-s01' WHERE id = 'uas20-q3';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-07-s01' WHERE id = 'uas24-q3';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-12-s00' WHERE id = 'uas24-q7';
UPDATE quiz_questions SET remediation_slide_id = 'UAS-03-s01' WHERE id = 'uas24-q9';
-- >>> ANCHORS END

-- ── 3. Corrective action records ────────────────────────────────────────────
-- question_id uses ON DELETE RESTRICT, not CASCADE: migrations 003/015/022 all
-- re-seed with `DELETE FROM quiz_questions WHERE module_id IN (...)`, and Admin ->
-- Modules can regenerate questions. Under CASCADE any of those would silently destroy
-- evidentiary records on a GA 509 licensing platform. question_text and
-- explanation_text are denormalized so a record stays legible if the question is
-- later reworded.
--
-- The key is (quiz_session_id, question_id), NOT (operator_id, module_id) as
-- report_submissions uses: a learner can critically fail the same module more than
-- once and each failure must produce its own record.
CREATE TABLE IF NOT EXISTS remediation_records (
  id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id       UUID        NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
  module_id         TEXT        NOT NULL REFERENCES mjm_modules(id),
  quiz_session_id   UUID        NOT NULL REFERENCES quiz_sessions(id) ON DELETE CASCADE,
  question_id       TEXT        NOT NULL REFERENCES quiz_questions(id) ON DELETE RESTRICT,
  question_text     TEXT        NOT NULL,
  explanation_text  TEXT,
  given_answer      TEXT,
  correct_answer    TEXT        NOT NULL,
  slide_id          TEXT,
  slide_viewed_at   TIMESTAMPTZ,
  note_error        TEXT        NOT NULL,
  note_standard     TEXT        NOT NULL,
  note_field_action TEXT        NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (quiz_session_id, question_id)
);

CREATE INDEX IF NOT EXISTS idx_remediation_operator_module
  ON remediation_records (operator_id, module_id);

-- RLS mirrors report_submissions: operators read their own, privileged roles read
-- all, and there are NO INSERT/UPDATE policies — every write goes through the
-- service role in the API route.
ALTER TABLE remediation_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "remediation_records_select" ON remediation_records;
CREATE POLICY "remediation_records_select" ON remediation_records
  FOR SELECT
  USING (
    auth.uid() = operator_id
    OR EXISTS (
      SELECT 1 FROM operators
      WHERE operators.id = auth.uid()
        AND operators.role IN ('super_admin', 'admin', 'coordinator')
    )
  );

GRANT SELECT ON remediation_records TO authenticated;

-- ── 4. Copy that lives in the database ──────────────────────────────────────
-- The PI-24 and UAS-24 capstone descriptions promise a 24-hour cooldown that will no
-- longer exist. Set by 009/017, which have already run, so an explicit UPDATE is the
-- only way to change them.
UPDATE mjm_modules
SET description = replace(
  description,
  'Three critical questions — any wrong answer triggers 24-hour cooldown.',
  'Three critical questions — any wrong answer requires a written corrective action before re-attempting.'
)
WHERE description LIKE '%24-hour cooldown%';

-- ── Verification ────────────────────────────────────────────────────────────
-- 1. Every slide has an id (expect total = with_id on all 64 rows):
--      SELECT module_id, jsonb_array_length(slides) AS total,
--             (SELECT count(*) FROM jsonb_array_elements(slides) s
--               WHERE s.value ? 'slideId') AS with_id
--      FROM module_lessons ORDER BY module_id;
--
-- 2. No cooldown copy survives (expect 0 rows):
--      SELECT id FROM mjm_modules WHERE description ILIKE '%cooldown%';
--
-- 3. Every anchor resolves to a real slide (expect 0 rows):
--      SELECT q.id, q.remediation_slide_id FROM quiz_questions q
--      WHERE q.is_critical AND q.remediation_slide_id IS NOT NULL
--        AND NOT EXISTS (
--          SELECT 1 FROM module_lessons ml, jsonb_array_elements(ml.slides) s
--          WHERE s.value->>'slideId' = q.remediation_slide_id);
--
-- 4. Anchor count (expect 65 of 65 — every critical question is anchored, 7 of
--    them cross-module; none ships unanchored):
--      SELECT count(*) FROM quiz_questions
--      WHERE is_critical AND remediation_slide_id IS NOT NULL;
--
-- 5. Cross-module anchors resolve to an EARLIER module in the SAME track (expect
--    0 rows — this is the constraint apply-remediation-anchors.mjs enforces):
--      SELECT q.id, q.module_id, q.remediation_slide_id
--      FROM quiz_questions q
--      JOIN mjm_modules qm ON qm.id = q.module_id
--      JOIN mjm_modules sm ON sm.id = regexp_replace(q.remediation_slide_id, '-s[0-9]+$', '')
--      WHERE q.is_critical AND q.remediation_slide_id IS NOT NULL
--        AND (sm.track <> qm.track OR sm.sequence_order > qm.sequence_order);
